// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/models/shared"
	"net/http"
)

type CancelExecutionRequest struct {
	ExecutionID string `pathParam:"style=simple,explode=false,name=execution_id"`
}

func (o *CancelExecutionRequest) GetExecutionID() string {
	if o == nil {
		return ""
	}
	return o.ExecutionID
}

// CancelExecutionResponseBody - The requested resource is forbidden
type CancelExecutionResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (o *CancelExecutionResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *CancelExecutionResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type CancelExecutionResponse struct {
	// The cancelled execution
	AutomationExecution *shared.AutomationExecution
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource is forbidden
	Object *CancelExecutionResponseBody
}

func (o *CancelExecutionResponse) GetAutomationExecution() *shared.AutomationExecution {
	if o == nil {
		return nil
	}
	return o.AutomationExecution
}

func (o *CancelExecutionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CancelExecutionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CancelExecutionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CancelExecutionResponse) GetObject() *CancelExecutionResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
