// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteFlowRequest struct {
	// Automation Workflow ID
	FlowID string `pathParam:"style=simple,explode=false,name=flow_id"`
}

func (o *DeleteFlowRequest) GetFlowID() string {
	if o == nil {
		return ""
	}
	return o.FlowID
}

// DeleteFlowResponseBody - The requested resource is forbidden
type DeleteFlowResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (o *DeleteFlowResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *DeleteFlowResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type DeleteFlowResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource is forbidden
	Object *DeleteFlowResponseBody
}

func (o *DeleteFlowResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteFlowResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteFlowResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteFlowResponse) GetObject() *DeleteFlowResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
