// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/models/shared"
	"net/http"
)

type GetExecutionRequest struct {
	ExecutionID string `pathParam:"style=simple,explode=false,name=execution_id"`
}

func (g *GetExecutionRequest) GetExecutionID() string {
	if g == nil {
		return ""
	}
	return g.ExecutionID
}

// GetExecutionResponseBody - The requested resource is forbidden
type GetExecutionResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (g *GetExecutionResponseBody) GetError() *string {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GetExecutionResponseBody) GetStatus() *int64 {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetExecutionResponse struct {
	// The returned execution
	AutomationExecution *shared.AutomationExecution
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource is forbidden
	Object *GetExecutionResponseBody
}

func (g *GetExecutionResponse) GetAutomationExecution() *shared.AutomationExecution {
	if g == nil {
		return nil
	}
	return g.AutomationExecution
}

func (g *GetExecutionResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetExecutionResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetExecutionResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetExecutionResponse) GetObject() *GetExecutionResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
