// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/models/shared"
	"net/http"
)

type GetExecutionsRequest struct {
	EntityID *string `queryParam:"style=form,explode=true,name=entity_id"`
	// Pagination: starting for results
	From *int64 `default:"0" queryParam:"style=form,explode=true,name=from"`
	// Include flow automations in the response
	IncludeFlows *bool `default:"false" queryParam:"style=form,explode=true,name=include_flows"`
	// Pagination: max number of results to return
	Size *int64 `default:"25" queryParam:"style=form,explode=true,name=size"`
}

func (g GetExecutionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetExecutionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetExecutionsRequest) GetEntityID() *string {
	if g == nil {
		return nil
	}
	return g.EntityID
}

func (g *GetExecutionsRequest) GetFrom() *int64 {
	if g == nil {
		return nil
	}
	return g.From
}

func (g *GetExecutionsRequest) GetIncludeFlows() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeFlows
}

func (g *GetExecutionsRequest) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

// GetExecutionsResponseBody - The requested resource is forbidden
type GetExecutionsResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (g *GetExecutionsResponseBody) GetError() *string {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GetExecutionsResponseBody) GetStatus() *int64 {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetExecutionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// List of automation executions
	GetExecutionsResp *shared.GetExecutionsResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource is forbidden
	Object *GetExecutionsResponseBody
}

func (g *GetExecutionsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetExecutionsResponse) GetGetExecutionsResp() *shared.GetExecutionsResp {
	if g == nil {
		return nil
	}
	return g.GetExecutionsResp
}

func (g *GetExecutionsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetExecutionsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetExecutionsResponse) GetObject() *GetExecutionsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
