// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/models/shared"
	"net/http"
)

type GetFlowRequest struct {
	// Automation Workflow ID
	FlowID string `pathParam:"style=simple,explode=false,name=flow_id"`
}

func (g *GetFlowRequest) GetFlowID() string {
	if g == nil {
		return ""
	}
	return g.FlowID
}

// GetFlowResponseBody - The requested resource is forbidden
type GetFlowResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (g *GetFlowResponseBody) GetError() *string {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GetFlowResponseBody) GetStatus() *int64 {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetFlowResponse struct {
	// The returned automation flow
	AutomationFlow *shared.AutomationFlow
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource is forbidden
	Object *GetFlowResponseBody
}

func (g *GetFlowResponse) GetAutomationFlow() *shared.AutomationFlow {
	if g == nil {
		return nil
	}
	return g.AutomationFlow
}

func (g *GetFlowResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetFlowResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetFlowResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetFlowResponse) GetObject() *GetFlowResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
