// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/models/shared"
	"net/http"
)

type RetriggerActionRequest struct {
	// Retry request details.
	RetryReq *shared.RetryReq `request:"mediaType=application/json"`
	// Id of Action to retry.
	ActionID string `pathParam:"style=simple,explode=false,name=action_id"`
	// Execution Id
	ExecutionID string `pathParam:"style=simple,explode=false,name=execution_id"`
}

func (r *RetriggerActionRequest) GetRetryReq() *shared.RetryReq {
	if r == nil {
		return nil
	}
	return r.RetryReq
}

func (r *RetriggerActionRequest) GetActionID() string {
	if r == nil {
		return ""
	}
	return r.ActionID
}

func (r *RetriggerActionRequest) GetExecutionID() string {
	if r == nil {
		return ""
	}
	return r.ExecutionID
}

// RetriggerActionResponseBody - The requested resource is forbidden
type RetriggerActionResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (r *RetriggerActionResponseBody) GetError() *string {
	if r == nil {
		return nil
	}
	return r.Error
}

func (r *RetriggerActionResponseBody) GetStatus() *int64 {
	if r == nil {
		return nil
	}
	return r.Status
}

type RetriggerActionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource is forbidden
	Object *RetriggerActionResponseBody
}

func (r *RetriggerActionResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RetriggerActionResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RetriggerActionResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *RetriggerActionResponse) GetObject() *RetriggerActionResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
