// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type APISubmissionTriggerConfiguration struct {
	SourceID *string `json:"source_id,omitempty"`
}

type APISubmissionTriggerTypeEnum string

const (
	APISubmissionTriggerTypeEnumAPISubmission APISubmissionTriggerTypeEnum = "api_submission"
)

func (e *APISubmissionTriggerTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "api_submission":
		*e = APISubmissionTriggerTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for APISubmissionTriggerTypeEnum: %s", s)
	}
}

type APISubmissionTrigger struct {
	Configuration APISubmissionTriggerConfiguration `json:"configuration"`
	Type          APISubmissionTriggerTypeEnum      `json:"type"`
}
