// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AssignUsersToStep struct {
	StepID   *string   `json:"step_id,omitempty"`
	StepName *string   `json:"step_name,omitempty"`
	UserIds  []float64 `json:"user_ids,omitempty"`
}
