// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type AutomationActionExecutionStateTypeEnum string

const (
	AutomationActionExecutionStateTypeEnumMapEntity AutomationActionExecutionStateTypeEnum = "map-entity"
)

func (e *AutomationActionExecutionStateTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "map-entity":
		*e = AutomationActionExecutionStateTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for AutomationActionExecutionStateTypeEnum: %s", s)
	}
}

type AutomationActionExecutionState struct {
	Config          *MapEntityConfig       `json:"config,omitempty"`
	ErrorOutput     *ErrorOutput           `json:"error_output,omitempty"`
	ExecutionStatus *ExecutionStatusEnum   `json:"execution_status,omitempty"`
	Outputs         map[string]interface{} `json:"outputs,omitempty"`
	// different behaviors for retrying failed execution actions.
	RetryStrategy *RetryStrategyEnum                      `json:"retry_strategy,omitempty"`
	StartedAt     *string                                 `json:"started_at,omitempty"`
	Type          *AutomationActionExecutionStateTypeEnum `json:"type,omitempty"`
	UpdatedAt     *string                                 `json:"updated_at,omitempty"`
}
