// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type CartCheckoutActionConfigReason struct {
	// Why the action has to be skipped/failed
	Message *string `json:"message,omitempty"`
	// Extra metadata about the skipping reason - such as a certain condition not met, etc.
	Payload map[string]interface{} `json:"payload,omitempty"`
}

func (o *CartCheckoutActionConfigReason) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CartCheckoutActionConfigReason) GetPayload() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Payload
}

type CartCheckoutActionConfigType string

const (
	CartCheckoutActionConfigTypeCartCheckout CartCheckoutActionConfigType = "cart-checkout"
)

func (e CartCheckoutActionConfigType) ToPointer() *CartCheckoutActionConfigType {
	return &e
}

func (e *CartCheckoutActionConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cart-checkout":
		*e = CartCheckoutActionConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CartCheckoutActionConfigType: %v", v)
	}
}

// CartCheckoutActionConfig - Creates an order entity with prices from journey
type CartCheckoutActionConfig struct {
	// Whether to stop execution in a failed state if this action fails
	AllowFailure *bool               `json:"allow_failure,omitempty"`
	Config       *CartCheckoutConfig `json:"config,omitempty"`
	// Flag indicating whether the action was created automatically or manually
	CreatedAutomatically *bool                           `json:"created_automatically,omitempty"`
	FlowActionID         *string                         `json:"flow_action_id,omitempty"`
	ID                   *string                         `json:"id,omitempty"`
	Name                 *string                         `json:"name,omitempty"`
	Reason               *CartCheckoutActionConfigReason `json:"reason,omitempty"`
	Type                 *CartCheckoutActionConfigType   `json:"type,omitempty"`
}

func (o *CartCheckoutActionConfig) GetAllowFailure() *bool {
	if o == nil {
		return nil
	}
	return o.AllowFailure
}

func (o *CartCheckoutActionConfig) GetConfig() *CartCheckoutConfig {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *CartCheckoutActionConfig) GetCreatedAutomatically() *bool {
	if o == nil {
		return nil
	}
	return o.CreatedAutomatically
}

func (o *CartCheckoutActionConfig) GetFlowActionID() *string {
	if o == nil {
		return nil
	}
	return o.FlowActionID
}

func (o *CartCheckoutActionConfig) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CartCheckoutActionConfig) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CartCheckoutActionConfig) GetReason() *CartCheckoutActionConfigReason {
	if o == nil {
		return nil
	}
	return o.Reason
}

func (o *CartCheckoutActionConfig) GetType() *CartCheckoutActionConfigType {
	if o == nil {
		return nil
	}
	return o.Type
}
