// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
)

type CartCheckoutConfigMappingAttributesType string

const (
	CartCheckoutConfigMappingAttributesTypeMappingAttributeV2 CartCheckoutConfigMappingAttributesType = "MappingAttributeV2"
	CartCheckoutConfigMappingAttributesTypeMappingAttribute   CartCheckoutConfigMappingAttributesType = "MappingAttribute"
)

type CartCheckoutConfigMappingAttributes struct {
	MappingAttributeV2 *MappingAttributeV2
	MappingAttribute   *MappingAttribute

	Type CartCheckoutConfigMappingAttributesType
}

func CreateCartCheckoutConfigMappingAttributesMappingAttributeV2(mappingAttributeV2 MappingAttributeV2) CartCheckoutConfigMappingAttributes {
	typ := CartCheckoutConfigMappingAttributesTypeMappingAttributeV2

	return CartCheckoutConfigMappingAttributes{
		MappingAttributeV2: &mappingAttributeV2,
		Type:               typ,
	}
}

func CreateCartCheckoutConfigMappingAttributesMappingAttribute(mappingAttribute MappingAttribute) CartCheckoutConfigMappingAttributes {
	typ := CartCheckoutConfigMappingAttributesTypeMappingAttribute

	return CartCheckoutConfigMappingAttributes{
		MappingAttribute: &mappingAttribute,
		Type:             typ,
	}
}

func (u *CartCheckoutConfigMappingAttributes) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	mappingAttributeV2 := new(MappingAttributeV2)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&mappingAttributeV2); err == nil {
		u.MappingAttributeV2 = mappingAttributeV2
		u.Type = CartCheckoutConfigMappingAttributesTypeMappingAttributeV2
		return nil
	}

	mappingAttribute := new(MappingAttribute)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&mappingAttribute); err == nil {
		u.MappingAttribute = mappingAttribute
		u.Type = CartCheckoutConfigMappingAttributesTypeMappingAttribute
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u CartCheckoutConfigMappingAttributes) MarshalJSON() ([]byte, error) {
	if u.MappingAttributeV2 != nil {
		return json.Marshal(u.MappingAttributeV2)
	}

	if u.MappingAttribute != nil {
		return json.Marshal(u.MappingAttribute)
	}

	return nil, nil
}

type CartCheckoutConfig struct {
	// Relation attribute on the main entity where the target entity will be linked. Set to false to disable linkback
	//
	LinkbackRelationAttribute *string `json:"linkback_relation_attribute,omitempty"`
	// Relation tags (labels) to include in main entity linkback relation attribute
	LinkbackRelationTags []string                              `json:"linkback_relation_tags,omitempty"`
	MappingAttributes    []CartCheckoutConfigMappingAttributes `json:"mapping_attributes,omitempty"`
	MappingConfig        *MappingConfigRef                     `json:"mapping_config,omitempty"`
	RelationAttributes   []RelationAttribute                   `json:"relation_attributes,omitempty"`
	// Unique key for target entity (see upsertEntity of Entity API)
	TargetUnique []string `json:"target_unique,omitempty"`
	// Version of the config
	Version *string `json:"version,omitempty"`
}
