// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ComparisonEnum string

const (
	ComparisonEnumEquals   ComparisonEnum = "equals"
	ComparisonEnumAnyOf    ComparisonEnum = "any_of"
	ComparisonEnumNotEmpty ComparisonEnum = "not_empty"
	ComparisonEnumIsEmpty  ComparisonEnum = "is_empty"
)

func (e ComparisonEnum) ToPointer() *ComparisonEnum {
	return &e
}

func (e *ComparisonEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "equals":
		fallthrough
	case "any_of":
		fallthrough
	case "not_empty":
		fallthrough
	case "is_empty":
		*e = ComparisonEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ComparisonEnum: %v", v)
	}
}
