// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type CreateDocumentActionConfigType string

const (
	CreateDocumentActionConfigTypeCreateDocument CreateDocumentActionConfigType = "create-document"
)

func (e CreateDocumentActionConfigType) ToPointer() *CreateDocumentActionConfigType {
	return &e
}

func (e *CreateDocumentActionConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "create-document":
		*e = CreateDocumentActionConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateDocumentActionConfigType: %v", v)
	}
}

type CreateDocumentActionConfig struct {
	// Whether to stop execution in a failed state if this action fails
	AllowFailure *bool                 `json:"allow_failure,omitempty"`
	Config       *CreateDocumentConfig `json:"config,omitempty"`
	// Flag indicating whether the action was created automatically or manually
	CreatedAutomatically *bool                           `json:"created_automatically,omitempty"`
	FlowActionID         *string                         `json:"flow_action_id,omitempty"`
	ID                   *string                         `json:"id,omitempty"`
	Name                 *string                         `json:"name,omitempty"`
	Type                 *CreateDocumentActionConfigType `json:"type,omitempty"`
}
