// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// MappingAttributeModeEnum - - copy_if_exists - it replaces the target attribute with the source value - append_if_exists - it currently replaces target attribute with array like values. Useful when you have multiple values to be added into one attribute. - set_value - it sets a value to a predefined value. Must be used together with value property.
type MappingAttributeModeEnum string

const (
	MappingAttributeModeEnumCopyIfExists   MappingAttributeModeEnum = "copy_if_exists"
	MappingAttributeModeEnumAppendIfExists MappingAttributeModeEnum = "append_if_exists"
	MappingAttributeModeEnumSetValue       MappingAttributeModeEnum = "set_value"
)

func (e *MappingAttributeModeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "copy_if_exists":
		fallthrough
	case "append_if_exists":
		fallthrough
	case "set_value":
		*e = MappingAttributeModeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for MappingAttributeModeEnum: %s", s)
	}
}
