// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MappingAttributeV2 struct {
	// Mapping operation nodes are either primitive values or operation node objects
	Operation OperationNode `json:"operation"`
	// Target JSON path for the attribute to set
	Target *string `json:"target,omitempty"`
}
