// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
)

type OperationNodeType string

const (
	OperationNodeTypeOperationObjectNode OperationNodeType = "OperationObjectNode"
	OperationNodeTypeAny                 OperationNodeType = "any"
)

type OperationNode struct {
	OperationObjectNode *OperationObjectNode
	Any                 interface{}

	Type OperationNodeType
}

func CreateOperationNodeOperationObjectNode(operationObjectNode OperationObjectNode) OperationNode {
	typ := OperationNodeTypeOperationObjectNode

	return OperationNode{
		OperationObjectNode: &operationObjectNode,
		Type:                typ,
	}
}

func CreateOperationNodeAny(any interface{}) OperationNode {
	typ := OperationNodeTypeAny

	return OperationNode{
		Any:  &any,
		Type: typ,
	}
}

func (u *OperationNode) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	operationObjectNode := new(OperationObjectNode)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&operationObjectNode); err == nil {
		u.OperationObjectNode = operationObjectNode
		u.Type = OperationNodeTypeOperationObjectNode
		return nil
	}

	any := new(interface{})
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&any); err == nil {
		u.Any = any
		u.Type = OperationNodeTypeAny
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u OperationNode) MarshalJSON() ([]byte, error) {
	if u.OperationObjectNode != nil {
		return json.Marshal(u.OperationObjectNode)
	}

	if u.Any != nil {
		return json.Marshal(u.Any)
	}

	return nil, nil
}
