// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OrCondition1 struct {
	DollarOr []FilterConditionOnEvent `json:"$or,omitempty"`
}

func (o *OrCondition1) GetDollarOr() []FilterConditionOnEvent {
	if o == nil {
		return nil
	}
	return o.DollarOr
}
