// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ReceivedEmailTriggerConfigurationMessageTypeEnum string

const (
	ReceivedEmailTriggerConfigurationMessageTypeEnumReceived ReceivedEmailTriggerConfigurationMessageTypeEnum = "RECEIVED"
)

func (e *ReceivedEmailTriggerConfigurationMessageTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "RECEIVED":
		*e = ReceivedEmailTriggerConfigurationMessageTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for ReceivedEmailTriggerConfigurationMessageTypeEnum: %s", s)
	}
}

type ReceivedEmailTriggerConfiguration struct {
	MessageType *ReceivedEmailTriggerConfigurationMessageTypeEnum `json:"message_type,omitempty"`
}

type ReceivedEmailTriggerTypeEnum string

const (
	ReceivedEmailTriggerTypeEnumReceivedEmail ReceivedEmailTriggerTypeEnum = "received_email"
)

func (e *ReceivedEmailTriggerTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "received_email":
		*e = ReceivedEmailTriggerTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for ReceivedEmailTriggerTypeEnum: %s", s)
	}
}

type ReceivedEmailTrigger struct {
	Configuration ReceivedEmailTriggerConfiguration `json:"configuration"`
	Type          ReceivedEmailTriggerTypeEnum      `json:"type"`
}
