// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RetryReq struct {
	// different behaviors for retrying failed execution actions.
	RetryStrategy *RetryStrategy `json:"retry_strategy,omitempty"`
}

func (o *RetryReq) GetRetryStrategy() *RetryStrategy {
	if o == nil {
		return nil
	}
	return o.RetryStrategy
}
