// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RetryReq - Retry request details.
type RetryReq struct {
	// different behaviors for retrying failed execution actions.
	RetryStrategy *RetryStrategy `json:"retry_strategy,omitempty"`
}
