// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TriggerWebhookConfig struct {
	EntitySources   []string `json:"entity_sources,omitempty"`
	TargetWebhookID *string  `json:"target_webhook_id,omitempty"`
}
