// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TriggerWorkflowActionConfigType string

const (
	TriggerWorkflowActionConfigTypeTriggerWorkflow TriggerWorkflowActionConfigType = "trigger-workflow"
)

func (e TriggerWorkflowActionConfigType) ToPointer() *TriggerWorkflowActionConfigType {
	return &e
}

func (e *TriggerWorkflowActionConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "trigger-workflow":
		*e = TriggerWorkflowActionConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TriggerWorkflowActionConfigType: %v", v)
	}
}

type TriggerWorkflowActionConfig struct {
	// Whether to stop execution in a failed state if this action fails
	AllowFailure *bool                  `json:"allow_failure,omitempty"`
	Config       *TriggerWorkflowConfig `json:"config,omitempty"`
	// Flag indicating whether the action was created automatically or manually
	CreatedAutomatically *bool                            `json:"created_automatically,omitempty"`
	FlowActionID         *string                          `json:"flow_action_id,omitempty"`
	ID                   *string                          `json:"id,omitempty"`
	Name                 *string                          `json:"name,omitempty"`
	Type                 *TriggerWorkflowActionConfigType `json:"type,omitempty"`
}
