// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Origin string

const (
	OriginTrigger    Origin = "trigger"
	OriginAction     Origin = "action"
	OriginActionTask Origin = "action_task"
	OriginAutomation Origin = "automation"
)

func (e Origin) ToPointer() *Origin {
	return &e
}
func (e *Origin) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "trigger":
		fallthrough
	case "action":
		fallthrough
	case "action_task":
		fallthrough
	case "automation":
		*e = Origin(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Origin: %v", v)
	}
}

// ActionScheduleSource - The source of the schedule_at timestamp that will be used to schedule the action
type ActionScheduleSource struct {
	Attribute *string `json:"attribute,omitempty"`
	// The id of the action or trigger
	ID     string  `json:"id"`
	Origin Origin  `json:"origin"`
	Schema *string `json:"schema,omitempty"`
}

func (a *ActionScheduleSource) GetAttribute() *string {
	if a == nil {
		return nil
	}
	return a.Attribute
}

func (a *ActionScheduleSource) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *ActionScheduleSource) GetOrigin() Origin {
	if a == nil {
		return Origin("")
	}
	return a.Origin
}

func (a *ActionScheduleSource) GetSchema() *string {
	if a == nil {
		return nil
	}
	return a.Schema
}
