// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ActionCondition struct {
	// Result of the condition evaluation
	EvaluationResult *bool   `json:"evaluationResult,omitempty"`
	ID               *string `json:"id,omitempty"`
	// Schedule Id which indicates the schedule of the actions inside the condition
	ScheduleID *string              `json:"schedule_id,omitempty"`
	Statements []ConditionStatement `json:"statements,omitempty"`
}

func (o *ActionCondition) GetEvaluationResult() *bool {
	if o == nil {
		return nil
	}
	return o.EvaluationResult
}

func (o *ActionCondition) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ActionCondition) GetScheduleID() *string {
	if o == nil {
		return nil
	}
	return o.ScheduleID
}

func (o *ActionCondition) GetStatements() []ConditionStatement {
	if o == nil {
		return nil
	}
	return o.Statements
}
