// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type AnyActionType string

const (
	AnyActionTypeMapEntityAction           AnyActionType = "MapEntityAction"
	AnyActionTypeTriggerWorkflowAction     AnyActionType = "TriggerWorkflowAction"
	AnyActionTypeTriggerShareEntityAction  AnyActionType = "TriggerShareEntityAction"
	AnyActionTypeTriggerWebhookAction      AnyActionType = "TriggerWebhookAction"
	AnyActionTypeInformERPAction           AnyActionType = "InformERPAction"
	AnyActionTypeCreateDocumentAction      AnyActionType = "CreateDocumentAction"
	AnyActionTypeSendEmailAction           AnyActionType = "SendEmailAction"
	AnyActionTypeCartCheckoutAction        AnyActionType = "CartCheckoutAction"
	AnyActionTypeCustomAction              AnyActionType = "CustomAction"
	AnyActionTypeAutomationAction          AnyActionType = "AutomationAction"
	AnyActionTypeFlowExecutionCancelAction AnyActionType = "FlowExecutionCancelAction"
)

type AnyAction struct {
	MapEntityAction           *MapEntityAction           `queryParam:"inline,name=AnyAction" union:"member"`
	TriggerWorkflowAction     *TriggerWorkflowAction     `queryParam:"inline,name=AnyAction" union:"member"`
	TriggerShareEntityAction  *TriggerShareEntityAction  `queryParam:"inline,name=AnyAction" union:"member"`
	TriggerWebhookAction      *TriggerWebhookAction      `queryParam:"inline,name=AnyAction" union:"member"`
	InformERPAction           *InformERPAction           `queryParam:"inline,name=AnyAction" union:"member"`
	CreateDocumentAction      *CreateDocumentAction      `queryParam:"inline,name=AnyAction" union:"member"`
	SendEmailAction           *SendEmailAction           `queryParam:"inline,name=AnyAction" union:"member"`
	CartCheckoutAction        *CartCheckoutAction        `queryParam:"inline,name=AnyAction" union:"member"`
	CustomAction              *CustomAction              `queryParam:"inline,name=AnyAction" union:"member"`
	AutomationAction          *AutomationAction          `queryParam:"inline,name=AnyAction" union:"member"`
	FlowExecutionCancelAction *FlowExecutionCancelAction `queryParam:"inline,name=AnyAction" union:"member"`

	Type AnyActionType
}

func CreateAnyActionMapEntityAction(mapEntityAction MapEntityAction) AnyAction {
	typ := AnyActionTypeMapEntityAction

	return AnyAction{
		MapEntityAction: &mapEntityAction,
		Type:            typ,
	}
}

func CreateAnyActionTriggerWorkflowAction(triggerWorkflowAction TriggerWorkflowAction) AnyAction {
	typ := AnyActionTypeTriggerWorkflowAction

	return AnyAction{
		TriggerWorkflowAction: &triggerWorkflowAction,
		Type:                  typ,
	}
}

func CreateAnyActionTriggerShareEntityAction(triggerShareEntityAction TriggerShareEntityAction) AnyAction {
	typ := AnyActionTypeTriggerShareEntityAction

	return AnyAction{
		TriggerShareEntityAction: &triggerShareEntityAction,
		Type:                     typ,
	}
}

func CreateAnyActionTriggerWebhookAction(triggerWebhookAction TriggerWebhookAction) AnyAction {
	typ := AnyActionTypeTriggerWebhookAction

	return AnyAction{
		TriggerWebhookAction: &triggerWebhookAction,
		Type:                 typ,
	}
}

func CreateAnyActionInformERPAction(informERPAction InformERPAction) AnyAction {
	typ := AnyActionTypeInformERPAction

	return AnyAction{
		InformERPAction: &informERPAction,
		Type:            typ,
	}
}

func CreateAnyActionCreateDocumentAction(createDocumentAction CreateDocumentAction) AnyAction {
	typ := AnyActionTypeCreateDocumentAction

	return AnyAction{
		CreateDocumentAction: &createDocumentAction,
		Type:                 typ,
	}
}

func CreateAnyActionSendEmailAction(sendEmailAction SendEmailAction) AnyAction {
	typ := AnyActionTypeSendEmailAction

	return AnyAction{
		SendEmailAction: &sendEmailAction,
		Type:            typ,
	}
}

func CreateAnyActionCartCheckoutAction(cartCheckoutAction CartCheckoutAction) AnyAction {
	typ := AnyActionTypeCartCheckoutAction

	return AnyAction{
		CartCheckoutAction: &cartCheckoutAction,
		Type:               typ,
	}
}

func CreateAnyActionCustomAction(customAction CustomAction) AnyAction {
	typ := AnyActionTypeCustomAction

	return AnyAction{
		CustomAction: &customAction,
		Type:         typ,
	}
}

func CreateAnyActionAutomationAction(automationAction AutomationAction) AnyAction {
	typ := AnyActionTypeAutomationAction

	return AnyAction{
		AutomationAction: &automationAction,
		Type:             typ,
	}
}

func CreateAnyActionFlowExecutionCancelAction(flowExecutionCancelAction FlowExecutionCancelAction) AnyAction {
	typ := AnyActionTypeFlowExecutionCancelAction

	return AnyAction{
		FlowExecutionCancelAction: &flowExecutionCancelAction,
		Type:                      typ,
	}
}

func (u *AnyAction) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var mapEntityAction MapEntityAction = MapEntityAction{}
	if err := utils.UnmarshalJSON(data, &mapEntityAction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyActionTypeMapEntityAction,
			Value: &mapEntityAction,
		})
	}

	var triggerWorkflowAction TriggerWorkflowAction = TriggerWorkflowAction{}
	if err := utils.UnmarshalJSON(data, &triggerWorkflowAction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyActionTypeTriggerWorkflowAction,
			Value: &triggerWorkflowAction,
		})
	}

	var triggerShareEntityAction TriggerShareEntityAction = TriggerShareEntityAction{}
	if err := utils.UnmarshalJSON(data, &triggerShareEntityAction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyActionTypeTriggerShareEntityAction,
			Value: &triggerShareEntityAction,
		})
	}

	var triggerWebhookAction TriggerWebhookAction = TriggerWebhookAction{}
	if err := utils.UnmarshalJSON(data, &triggerWebhookAction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyActionTypeTriggerWebhookAction,
			Value: &triggerWebhookAction,
		})
	}

	var informERPAction InformERPAction = InformERPAction{}
	if err := utils.UnmarshalJSON(data, &informERPAction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyActionTypeInformERPAction,
			Value: &informERPAction,
		})
	}

	var createDocumentAction CreateDocumentAction = CreateDocumentAction{}
	if err := utils.UnmarshalJSON(data, &createDocumentAction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyActionTypeCreateDocumentAction,
			Value: &createDocumentAction,
		})
	}

	var sendEmailAction SendEmailAction = SendEmailAction{}
	if err := utils.UnmarshalJSON(data, &sendEmailAction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyActionTypeSendEmailAction,
			Value: &sendEmailAction,
		})
	}

	var cartCheckoutAction CartCheckoutAction = CartCheckoutAction{}
	if err := utils.UnmarshalJSON(data, &cartCheckoutAction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyActionTypeCartCheckoutAction,
			Value: &cartCheckoutAction,
		})
	}

	var customAction CustomAction = CustomAction{}
	if err := utils.UnmarshalJSON(data, &customAction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyActionTypeCustomAction,
			Value: &customAction,
		})
	}

	var automationAction AutomationAction = AutomationAction{}
	if err := utils.UnmarshalJSON(data, &automationAction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyActionTypeAutomationAction,
			Value: &automationAction,
		})
	}

	var flowExecutionCancelAction FlowExecutionCancelAction = FlowExecutionCancelAction{}
	if err := utils.UnmarshalJSON(data, &flowExecutionCancelAction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyActionTypeFlowExecutionCancelAction,
			Value: &flowExecutionCancelAction,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for AnyAction", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for AnyAction", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(AnyActionType)
	switch best.Type {
	case AnyActionTypeMapEntityAction:
		u.MapEntityAction = best.Value.(*MapEntityAction)
		return nil
	case AnyActionTypeTriggerWorkflowAction:
		u.TriggerWorkflowAction = best.Value.(*TriggerWorkflowAction)
		return nil
	case AnyActionTypeTriggerShareEntityAction:
		u.TriggerShareEntityAction = best.Value.(*TriggerShareEntityAction)
		return nil
	case AnyActionTypeTriggerWebhookAction:
		u.TriggerWebhookAction = best.Value.(*TriggerWebhookAction)
		return nil
	case AnyActionTypeInformERPAction:
		u.InformERPAction = best.Value.(*InformERPAction)
		return nil
	case AnyActionTypeCreateDocumentAction:
		u.CreateDocumentAction = best.Value.(*CreateDocumentAction)
		return nil
	case AnyActionTypeSendEmailAction:
		u.SendEmailAction = best.Value.(*SendEmailAction)
		return nil
	case AnyActionTypeCartCheckoutAction:
		u.CartCheckoutAction = best.Value.(*CartCheckoutAction)
		return nil
	case AnyActionTypeCustomAction:
		u.CustomAction = best.Value.(*CustomAction)
		return nil
	case AnyActionTypeAutomationAction:
		u.AutomationAction = best.Value.(*AutomationAction)
		return nil
	case AnyActionTypeFlowExecutionCancelAction:
		u.FlowExecutionCancelAction = best.Value.(*FlowExecutionCancelAction)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AnyAction", string(data))
}

func (u AnyAction) MarshalJSON() ([]byte, error) {
	if u.MapEntityAction != nil {
		return utils.MarshalJSON(u.MapEntityAction, "", true)
	}

	if u.TriggerWorkflowAction != nil {
		return utils.MarshalJSON(u.TriggerWorkflowAction, "", true)
	}

	if u.TriggerShareEntityAction != nil {
		return utils.MarshalJSON(u.TriggerShareEntityAction, "", true)
	}

	if u.TriggerWebhookAction != nil {
		return utils.MarshalJSON(u.TriggerWebhookAction, "", true)
	}

	if u.InformERPAction != nil {
		return utils.MarshalJSON(u.InformERPAction, "", true)
	}

	if u.CreateDocumentAction != nil {
		return utils.MarshalJSON(u.CreateDocumentAction, "", true)
	}

	if u.SendEmailAction != nil {
		return utils.MarshalJSON(u.SendEmailAction, "", true)
	}

	if u.CartCheckoutAction != nil {
		return utils.MarshalJSON(u.CartCheckoutAction, "", true)
	}

	if u.CustomAction != nil {
		return utils.MarshalJSON(u.CustomAction, "", true)
	}

	if u.AutomationAction != nil {
		return utils.MarshalJSON(u.AutomationAction, "", true)
	}

	if u.FlowExecutionCancelAction != nil {
		return utils.MarshalJSON(u.FlowExecutionCancelAction, "", true)
	}

	return nil, errors.New("could not marshal union type AnyAction: all fields are null")
}
