// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type AnyTriggerType string

const (
	AnyTriggerTypeFrontendSubmitTrigger  AnyTriggerType = "FrontendSubmitTrigger"
	AnyTriggerTypeJourneySubmitTrigger   AnyTriggerType = "JourneySubmitTrigger"
	AnyTriggerTypeAPISubmissionTrigger   AnyTriggerType = "ApiSubmissionTrigger"
	AnyTriggerTypeEntityOperationTrigger AnyTriggerType = "EntityOperationTrigger"
	AnyTriggerTypeAny                    AnyTriggerType = "any"
	AnyTriggerTypeEntityManualTrigger    AnyTriggerType = "EntityManualTrigger"
	AnyTriggerTypeReceivedEmailTrigger   AnyTriggerType = "ReceivedEmailTrigger"
)

type AnyTrigger struct {
	FrontendSubmitTrigger  *FrontendSubmitTrigger
	JourneySubmitTrigger   *JourneySubmitTrigger
	APISubmissionTrigger   *APISubmissionTrigger
	EntityOperationTrigger *EntityOperationTrigger
	Any                    any
	EntityManualTrigger    *EntityManualTrigger
	ReceivedEmailTrigger   *ReceivedEmailTrigger

	Type AnyTriggerType
}

func CreateAnyTriggerFrontendSubmitTrigger(frontendSubmitTrigger FrontendSubmitTrigger) AnyTrigger {
	typ := AnyTriggerTypeFrontendSubmitTrigger

	return AnyTrigger{
		FrontendSubmitTrigger: &frontendSubmitTrigger,
		Type:                  typ,
	}
}

func CreateAnyTriggerJourneySubmitTrigger(journeySubmitTrigger JourneySubmitTrigger) AnyTrigger {
	typ := AnyTriggerTypeJourneySubmitTrigger

	return AnyTrigger{
		JourneySubmitTrigger: &journeySubmitTrigger,
		Type:                 typ,
	}
}

func CreateAnyTriggerAPISubmissionTrigger(apiSubmissionTrigger APISubmissionTrigger) AnyTrigger {
	typ := AnyTriggerTypeAPISubmissionTrigger

	return AnyTrigger{
		APISubmissionTrigger: &apiSubmissionTrigger,
		Type:                 typ,
	}
}

func CreateAnyTriggerEntityOperationTrigger(entityOperationTrigger EntityOperationTrigger) AnyTrigger {
	typ := AnyTriggerTypeEntityOperationTrigger

	return AnyTrigger{
		EntityOperationTrigger: &entityOperationTrigger,
		Type:                   typ,
	}
}

func CreateAnyTriggerAny(any any) AnyTrigger {
	typ := AnyTriggerTypeAny

	return AnyTrigger{
		Any:  any,
		Type: typ,
	}
}

func CreateAnyTriggerEntityManualTrigger(entityManualTrigger EntityManualTrigger) AnyTrigger {
	typ := AnyTriggerTypeEntityManualTrigger

	return AnyTrigger{
		EntityManualTrigger: &entityManualTrigger,
		Type:                typ,
	}
}

func CreateAnyTriggerReceivedEmailTrigger(receivedEmailTrigger ReceivedEmailTrigger) AnyTrigger {
	typ := AnyTriggerTypeReceivedEmailTrigger

	return AnyTrigger{
		ReceivedEmailTrigger: &receivedEmailTrigger,
		Type:                 typ,
	}
}

func (u *AnyTrigger) UnmarshalJSON(data []byte) error {

	var frontendSubmitTrigger FrontendSubmitTrigger = FrontendSubmitTrigger{}
	if err := utils.UnmarshalJSON(data, &frontendSubmitTrigger, "", true, false); err == nil {
		u.FrontendSubmitTrigger = &frontendSubmitTrigger
		u.Type = AnyTriggerTypeFrontendSubmitTrigger
		return nil
	}

	var journeySubmitTrigger JourneySubmitTrigger = JourneySubmitTrigger{}
	if err := utils.UnmarshalJSON(data, &journeySubmitTrigger, "", true, false); err == nil {
		u.JourneySubmitTrigger = &journeySubmitTrigger
		u.Type = AnyTriggerTypeJourneySubmitTrigger
		return nil
	}

	var apiSubmissionTrigger APISubmissionTrigger = APISubmissionTrigger{}
	if err := utils.UnmarshalJSON(data, &apiSubmissionTrigger, "", true, false); err == nil {
		u.APISubmissionTrigger = &apiSubmissionTrigger
		u.Type = AnyTriggerTypeAPISubmissionTrigger
		return nil
	}

	var entityOperationTrigger EntityOperationTrigger = EntityOperationTrigger{}
	if err := utils.UnmarshalJSON(data, &entityOperationTrigger, "", true, false); err == nil {
		u.EntityOperationTrigger = &entityOperationTrigger
		u.Type = AnyTriggerTypeEntityOperationTrigger
		return nil
	}

	var entityManualTrigger EntityManualTrigger = EntityManualTrigger{}
	if err := utils.UnmarshalJSON(data, &entityManualTrigger, "", true, false); err == nil {
		u.EntityManualTrigger = &entityManualTrigger
		u.Type = AnyTriggerTypeEntityManualTrigger
		return nil
	}

	var receivedEmailTrigger ReceivedEmailTrigger = ReceivedEmailTrigger{}
	if err := utils.UnmarshalJSON(data, &receivedEmailTrigger, "", true, false); err == nil {
		u.ReceivedEmailTrigger = &receivedEmailTrigger
		u.Type = AnyTriggerTypeReceivedEmailTrigger
		return nil
	}

	var any any = nil
	if err := utils.UnmarshalJSON(data, &any, "", true, false); err == nil {
		u.Any = any
		u.Type = AnyTriggerTypeAny
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AnyTrigger", string(data))
}

func (u AnyTrigger) MarshalJSON() ([]byte, error) {
	if u.FrontendSubmitTrigger != nil {
		return utils.MarshalJSON(u.FrontendSubmitTrigger, "", true)
	}

	if u.JourneySubmitTrigger != nil {
		return utils.MarshalJSON(u.JourneySubmitTrigger, "", true)
	}

	if u.APISubmissionTrigger != nil {
		return utils.MarshalJSON(u.APISubmissionTrigger, "", true)
	}

	if u.EntityOperationTrigger != nil {
		return utils.MarshalJSON(u.EntityOperationTrigger, "", true)
	}

	if u.Any != nil {
		return utils.MarshalJSON(u.Any, "", true)
	}

	if u.EntityManualTrigger != nil {
		return utils.MarshalJSON(u.EntityManualTrigger, "", true)
	}

	if u.ReceivedEmailTrigger != nil {
		return utils.MarshalJSON(u.ReceivedEmailTrigger, "", true)
	}

	return nil, errors.New("could not marshal union type AnyTrigger: all fields are null")
}
