// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type Configuration struct {
	SourceID *string `json:"source_id,omitempty"`
}

func (c Configuration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Configuration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Configuration) GetSourceID() *string {
	if c == nil {
		return nil
	}
	return c.SourceID
}

type Type string

const (
	TypeAPISubmission Type = "api_submission"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "api_submission":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type APISubmissionTrigger struct {
	Configuration Configuration `json:"configuration"`
	ID            *string       `json:"id,omitempty"`
	Type          Type          `json:"type"`
}

func (a APISubmissionTrigger) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APISubmissionTrigger) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APISubmissionTrigger) GetConfiguration() Configuration {
	if a == nil {
		return Configuration{}
	}
	return a.Configuration
}

func (a *APISubmissionTrigger) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *APISubmissionTrigger) GetType() Type {
	if a == nil {
		return Type("")
	}
	return a.Type
}
