// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type CreateDocumentConfig struct {
	Filename   *string `json:"filename,omitempty"`
	TemplateID *string `json:"template_id,omitempty"`
}

func (c CreateDocumentConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateDocumentConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateDocumentConfig) GetFilename() *string {
	if c == nil {
		return nil
	}
	return c.Filename
}

func (c *CreateDocumentConfig) GetTemplateID() *string {
	if c == nil {
		return nil
	}
	return c.TemplateID
}
