// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type EntitySearchFilterValueType string

const (
	EntitySearchFilterValueTypeStr     EntitySearchFilterValueType = "str"
	EntitySearchFilterValueTypeNumber  EntitySearchFilterValueType = "number"
	EntitySearchFilterValueTypeBoolean EntitySearchFilterValueType = "boolean"
)

// EntitySearchFilterValue - A filter field value.
type EntitySearchFilterValue struct {
	Str     *string  `queryParam:"inline" name:"EntitySearchFilterValue"`
	Number  *float64 `queryParam:"inline" name:"EntitySearchFilterValue"`
	Boolean *bool    `queryParam:"inline" name:"EntitySearchFilterValue"`

	Type EntitySearchFilterValueType
}

func CreateEntitySearchFilterValueStr(str string) EntitySearchFilterValue {
	typ := EntitySearchFilterValueTypeStr

	return EntitySearchFilterValue{
		Str:  &str,
		Type: typ,
	}
}

func CreateEntitySearchFilterValueNumber(number float64) EntitySearchFilterValue {
	typ := EntitySearchFilterValueTypeNumber

	return EntitySearchFilterValue{
		Number: &number,
		Type:   typ,
	}
}

func CreateEntitySearchFilterValueBoolean(boolean bool) EntitySearchFilterValue {
	typ := EntitySearchFilterValueTypeBoolean

	return EntitySearchFilterValue{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *EntitySearchFilterValue) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = EntitySearchFilterValueTypeStr
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = EntitySearchFilterValueTypeNumber
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = EntitySearchFilterValueTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for EntitySearchFilterValue", string(data))
}

func (u EntitySearchFilterValue) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type EntitySearchFilterValue: all fields are null")
}
