// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type EntitySearchFilterValueType string

const (
	EntitySearchFilterValueTypeStr     EntitySearchFilterValueType = "str"
	EntitySearchFilterValueTypeNumber  EntitySearchFilterValueType = "number"
	EntitySearchFilterValueTypeBoolean EntitySearchFilterValueType = "boolean"
)

// EntitySearchFilterValue - A filter field value.
type EntitySearchFilterValue struct {
	Str     *string  `queryParam:"inline,name=EntitySearchFilterValue" union:"member"`
	Number  *float64 `queryParam:"inline,name=EntitySearchFilterValue" union:"member"`
	Boolean *bool    `queryParam:"inline,name=EntitySearchFilterValue" union:"member"`

	Type EntitySearchFilterValueType
}

func CreateEntitySearchFilterValueStr(str string) EntitySearchFilterValue {
	typ := EntitySearchFilterValueTypeStr

	return EntitySearchFilterValue{
		Str:  &str,
		Type: typ,
	}
}

func CreateEntitySearchFilterValueNumber(number float64) EntitySearchFilterValue {
	typ := EntitySearchFilterValueTypeNumber

	return EntitySearchFilterValue{
		Number: &number,
		Type:   typ,
	}
}

func CreateEntitySearchFilterValueBoolean(boolean bool) EntitySearchFilterValue {
	typ := EntitySearchFilterValueTypeBoolean

	return EntitySearchFilterValue{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *EntitySearchFilterValue) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EntitySearchFilterValueTypeStr,
			Value: &str,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EntitySearchFilterValueTypeNumber,
			Value: &number,
		})
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EntitySearchFilterValueTypeBoolean,
			Value: &boolean,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for EntitySearchFilterValue", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for EntitySearchFilterValue", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(EntitySearchFilterValueType)
	switch best.Type {
	case EntitySearchFilterValueTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case EntitySearchFilterValueTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case EntitySearchFilterValueTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for EntitySearchFilterValue", string(data))
}

func (u EntitySearchFilterValue) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type EntitySearchFilterValue: all fields are null")
}
