// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EntityRef struct {
	EntityID     string `json:"entity_id"`
	EntitySchema string `json:"entity_schema"`
}

func (o *EntityRef) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

func (o *EntityRef) GetEntitySchema() string {
	if o == nil {
		return ""
	}
	return o.EntitySchema
}
