// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type EntityManualTriggerConfiguration struct {
	// Which entity type can this automation be triggered from
	Schema *string `json:"schema,omitempty"`
}

func (e EntityManualTriggerConfiguration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityManualTriggerConfiguration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *EntityManualTriggerConfiguration) GetSchema() *string {
	if o == nil {
		return nil
	}
	return o.Schema
}

type EntityManualTriggerType string

const (
	EntityManualTriggerTypeEntityManual EntityManualTriggerType = "entity_manual"
)

func (e EntityManualTriggerType) ToPointer() *EntityManualTriggerType {
	return &e
}
func (e *EntityManualTriggerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "entity_manual":
		*e = EntityManualTriggerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EntityManualTriggerType: %v", v)
	}
}

type EntityManualTrigger struct {
	Configuration EntityManualTriggerConfiguration `json:"configuration"`
	ID            *string                          `json:"id,omitempty"`
	Type          EntityManualTriggerType          `json:"type"`
}

func (e EntityManualTrigger) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityManualTrigger) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"configuration", "type"}); err != nil {
		return err
	}
	return nil
}

func (o *EntityManualTrigger) GetConfiguration() EntityManualTriggerConfiguration {
	if o == nil {
		return EntityManualTriggerConfiguration{}
	}
	return o.Configuration
}

func (o *EntityManualTrigger) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *EntityManualTrigger) GetType() EntityManualTriggerType {
	if o == nil {
		return EntityManualTriggerType("")
	}
	return o.Type
}
