// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type ErrorDetail struct {
	Context     *string `json:"context,omitempty"`
	Explanation string  `json:"explanation"`
	ID          *string `json:"id,omitempty"`
}

func (e ErrorDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ErrorDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ErrorDetail) GetContext() *string {
	if e == nil {
		return nil
	}
	return e.Context
}

func (e *ErrorDetail) GetExplanation() string {
	if e == nil {
		return ""
	}
	return e.Explanation
}

func (e *ErrorDetail) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}
