// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type ErrorInfo struct {
	AdditionalProperties any           `additionalProperties:"true" json:"-"`
	Details              []ErrorDetail `json:"details,omitempty"`
}

func (e ErrorInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ErrorInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ErrorInfo) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *ErrorInfo) GetDetails() []ErrorDetail {
	if o == nil {
		return nil
	}
	return o.Details
}

type ErrorOutput struct {
	ErrorCode   ErrorCode  `json:"error_code"`
	ErrorInfo   *ErrorInfo `json:"error_info,omitempty"`
	ErrorReason string     `json:"error_reason"`
}

func (o *ErrorOutput) GetErrorCode() ErrorCode {
	if o == nil {
		return ErrorCode("")
	}
	return o.ErrorCode
}

func (o *ErrorOutput) GetErrorInfo() *ErrorInfo {
	if o == nil {
		return nil
	}
	return o.ErrorInfo
}

func (o *ErrorOutput) GetErrorReason() string {
	if o == nil {
		return ""
	}
	return o.ErrorReason
}
