// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type ExistsCondition struct {
	Exists *bool `json:"exists,omitempty"`
}

func (e ExistsCondition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExistsCondition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ExistsCondition) GetExists() *bool {
	if o == nil {
		return nil
	}
	return o.Exists
}
