// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type FlowExecutionCancelActionReason struct {
	// Why the action has to be skipped/failed
	Message *string `json:"message,omitempty"`
	// Extra metadata about the skipping reason - such as a certain condition not met, etc.
	Payload map[string]any `json:"payload,omitempty"`
}

func (f FlowExecutionCancelActionReason) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowExecutionCancelActionReason) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FlowExecutionCancelActionReason) GetMessage() *string {
	if f == nil {
		return nil
	}
	return f.Message
}

func (f *FlowExecutionCancelActionReason) GetPayload() map[string]any {
	if f == nil {
		return nil
	}
	return f.Payload
}

type FlowExecutionCancelActionType string

const (
	FlowExecutionCancelActionTypeCancelFlowExecution FlowExecutionCancelActionType = "cancel-flow-execution"
)

func (e FlowExecutionCancelActionType) ToPointer() *FlowExecutionCancelActionType {
	return &e
}
func (e *FlowExecutionCancelActionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cancel-flow-execution":
		*e = FlowExecutionCancelActionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FlowExecutionCancelActionType: %v", v)
	}
}

type FlowExecutionCancelAction struct {
	// Whether to stop execution in a failed state if this action fails
	AllowFailure *bool `json:"allow_failure,omitempty"`
	// Condition Id to be checked before executing the action
	ConditionID *string `json:"condition_id,omitempty"`
	// Configuration for cancelling a flow execution with selected reasons
	Config *FlowExecutionCancelConfig `json:"config,omitempty"`
	// Flag indicating whether the action was created automatically or manually
	CreatedAutomatically *bool            `json:"created_automatically,omitempty"`
	ErrorOutput          *ErrorOutput     `json:"error_output,omitempty"`
	ExecutionStatus      *ExecutionStatus `json:"execution_status,omitempty"`
	FlowActionID         *string          `json:"flow_action_id,omitempty"`
	ID                   *string          `json:"id,omitempty"`
	// Flag indicating whether the same action can be in bulk in a single execution. e.g; send-email / map-entity
	IsBulkAction *bool                            `json:"is_bulk_action,omitempty"`
	Name         *string                          `json:"name,omitempty"`
	Outputs      map[string]any                   `json:"outputs,omitempty"`
	Reason       *FlowExecutionCancelActionReason `json:"reason,omitempty"`
	// different behaviors for retrying failed execution actions.
	RetryStrategy *RetryStrategy `json:"retry_strategy,omitempty"`
	// Schedule Id which indicates the schedule of the action
	ScheduleID *string                        `json:"schedule_id,omitempty"`
	StartedAt  *string                        `json:"started_at,omitempty"`
	Type       *FlowExecutionCancelActionType `json:"type,omitempty"`
	UpdatedAt  *string                        `json:"updated_at,omitempty"`
}

func (f FlowExecutionCancelAction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowExecutionCancelAction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FlowExecutionCancelAction) GetAllowFailure() *bool {
	if f == nil {
		return nil
	}
	return f.AllowFailure
}

func (f *FlowExecutionCancelAction) GetConditionID() *string {
	if f == nil {
		return nil
	}
	return f.ConditionID
}

func (f *FlowExecutionCancelAction) GetConfig() *FlowExecutionCancelConfig {
	if f == nil {
		return nil
	}
	return f.Config
}

func (f *FlowExecutionCancelAction) GetCreatedAutomatically() *bool {
	if f == nil {
		return nil
	}
	return f.CreatedAutomatically
}

func (f *FlowExecutionCancelAction) GetErrorOutput() *ErrorOutput {
	if f == nil {
		return nil
	}
	return f.ErrorOutput
}

func (f *FlowExecutionCancelAction) GetExecutionStatus() *ExecutionStatus {
	if f == nil {
		return nil
	}
	return f.ExecutionStatus
}

func (f *FlowExecutionCancelAction) GetFlowActionID() *string {
	if f == nil {
		return nil
	}
	return f.FlowActionID
}

func (f *FlowExecutionCancelAction) GetID() *string {
	if f == nil {
		return nil
	}
	return f.ID
}

func (f *FlowExecutionCancelAction) GetIsBulkAction() *bool {
	if f == nil {
		return nil
	}
	return f.IsBulkAction
}

func (f *FlowExecutionCancelAction) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}

func (f *FlowExecutionCancelAction) GetOutputs() map[string]any {
	if f == nil {
		return nil
	}
	return f.Outputs
}

func (f *FlowExecutionCancelAction) GetReason() *FlowExecutionCancelActionReason {
	if f == nil {
		return nil
	}
	return f.Reason
}

func (f *FlowExecutionCancelAction) GetRetryStrategy() *RetryStrategy {
	if f == nil {
		return nil
	}
	return f.RetryStrategy
}

func (f *FlowExecutionCancelAction) GetScheduleID() *string {
	if f == nil {
		return nil
	}
	return f.ScheduleID
}

func (f *FlowExecutionCancelAction) GetStartedAt() *string {
	if f == nil {
		return nil
	}
	return f.StartedAt
}

func (f *FlowExecutionCancelAction) GetType() *FlowExecutionCancelActionType {
	if f == nil {
		return nil
	}
	return f.Type
}

func (f *FlowExecutionCancelAction) GetUpdatedAt() *string {
	if f == nil {
		return nil
	}
	return f.UpdatedAt
}
