// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type FlowsTriggerConfiguration struct {
	// When Journeys are linked to Workflows V2 as Journey Automations, this field will contain the ID of the Journey
	JourneyID *string `json:"journey_id,omitempty"`
	// The ID of the workflow v2 that triggers this automation
	SourceID string `json:"source_id"`
}

func (f FlowsTriggerConfiguration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsTriggerConfiguration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"source_id"}); err != nil {
		return err
	}
	return nil
}

func (o *FlowsTriggerConfiguration) GetJourneyID() *string {
	if o == nil {
		return nil
	}
	return o.JourneyID
}

func (o *FlowsTriggerConfiguration) GetSourceID() string {
	if o == nil {
		return ""
	}
	return o.SourceID
}

type FlowsTriggerType string

const (
	FlowsTriggerTypeFlowsTrigger FlowsTriggerType = "flows_trigger"
)

func (e FlowsTriggerType) ToPointer() *FlowsTriggerType {
	return &e
}
func (e *FlowsTriggerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "flows_trigger":
		*e = FlowsTriggerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FlowsTriggerType: %v", v)
	}
}

type FlowsTrigger struct {
	Configuration FlowsTriggerConfiguration `json:"configuration"`
	ID            *string                   `json:"id,omitempty"`
	Type          FlowsTriggerType          `json:"type"`
}

func (f FlowsTrigger) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsTrigger) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"configuration", "type"}); err != nil {
		return err
	}
	return nil
}

func (o *FlowsTrigger) GetConfiguration() FlowsTriggerConfiguration {
	if o == nil {
		return FlowsTriggerConfiguration{}
	}
	return o.Configuration
}

func (o *FlowsTrigger) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *FlowsTrigger) GetType() FlowsTriggerType {
	if o == nil {
		return FlowsTriggerType("")
	}
	return o.Type
}
