// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type MapEntityConfigMappingAttributesType string

const (
	MapEntityConfigMappingAttributesTypeMappingAttributeV2 MapEntityConfigMappingAttributesType = "MappingAttributeV2"
	MapEntityConfigMappingAttributesTypeMappingAttribute   MapEntityConfigMappingAttributesType = "MappingAttribute"
)

type MapEntityConfigMappingAttributes struct {
	MappingAttributeV2 *MappingAttributeV2 `queryParam:"inline,name=mapping_attributes" union:"member"`
	MappingAttribute   *MappingAttribute   `queryParam:"inline,name=mapping_attributes" union:"member"`

	Type MapEntityConfigMappingAttributesType
}

func CreateMapEntityConfigMappingAttributesMappingAttributeV2(mappingAttributeV2 MappingAttributeV2) MapEntityConfigMappingAttributes {
	typ := MapEntityConfigMappingAttributesTypeMappingAttributeV2

	return MapEntityConfigMappingAttributes{
		MappingAttributeV2: &mappingAttributeV2,
		Type:               typ,
	}
}

func CreateMapEntityConfigMappingAttributesMappingAttribute(mappingAttribute MappingAttribute) MapEntityConfigMappingAttributes {
	typ := MapEntityConfigMappingAttributesTypeMappingAttribute

	return MapEntityConfigMappingAttributes{
		MappingAttribute: &mappingAttribute,
		Type:             typ,
	}
}

func (u *MapEntityConfigMappingAttributes) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var mappingAttributeV2 MappingAttributeV2 = MappingAttributeV2{}
	if err := utils.UnmarshalJSON(data, &mappingAttributeV2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MapEntityConfigMappingAttributesTypeMappingAttributeV2,
			Value: &mappingAttributeV2,
		})
	}

	var mappingAttribute MappingAttribute = MappingAttribute{}
	if err := utils.UnmarshalJSON(data, &mappingAttribute, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MapEntityConfigMappingAttributesTypeMappingAttribute,
			Value: &mappingAttribute,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MapEntityConfigMappingAttributes", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MapEntityConfigMappingAttributes", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(MapEntityConfigMappingAttributesType)
	switch best.Type {
	case MapEntityConfigMappingAttributesTypeMappingAttributeV2:
		u.MappingAttributeV2 = best.Value.(*MappingAttributeV2)
		return nil
	case MapEntityConfigMappingAttributesTypeMappingAttribute:
		u.MappingAttribute = best.Value.(*MappingAttribute)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for MapEntityConfigMappingAttributes", string(data))
}

func (u MapEntityConfigMappingAttributes) MarshalJSON() ([]byte, error) {
	if u.MappingAttributeV2 != nil {
		return utils.MarshalJSON(u.MappingAttributeV2, "", true)
	}

	if u.MappingAttribute != nil {
		return utils.MarshalJSON(u.MappingAttribute, "", true)
	}

	return nil, errors.New("could not marshal union type MapEntityConfigMappingAttributes: all fields are null")
}

type MapEntityConfig struct {
	// Relation attribute on the main entity where the target entity will be linked. Set to false to disable linkback
	//
	LinkbackRelationAttribute *string `default:"mapped_entities" json:"linkback_relation_attribute"`
	// Relation tags (labels) to include in main entity linkback relation attribute
	LinkbackRelationTags []string `json:"linkback_relation_tags,omitempty"`
	// Attribute mappings
	MappingAttributes []MapEntityConfigMappingAttributes `json:"mapping_attributes,omitempty"`
	MappingConfig     *MappingConfigRef                  `json:"mapping_config,omitempty"`
	// Relation mappings
	RelationAttributes []RelationAttribute `json:"relation_attributes,omitempty"`
	// Schema of target entity
	TargetSchema string `json:"target_schema"`
	// Unique key for target entity (see upsertEntity of Entity API)
	TargetUnique []string `json:"target_unique,omitempty"`
}

func (m MapEntityConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MapEntityConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MapEntityConfig) GetLinkbackRelationAttribute() *string {
	if m == nil {
		return nil
	}
	return m.LinkbackRelationAttribute
}

func (m *MapEntityConfig) GetLinkbackRelationTags() []string {
	if m == nil {
		return nil
	}
	return m.LinkbackRelationTags
}

func (m *MapEntityConfig) GetMappingAttributes() []MapEntityConfigMappingAttributes {
	if m == nil {
		return nil
	}
	return m.MappingAttributes
}

func (m *MapEntityConfig) GetMappingConfig() *MappingConfigRef {
	if m == nil {
		return nil
	}
	return m.MappingConfig
}

func (m *MapEntityConfig) GetRelationAttributes() []RelationAttribute {
	if m == nil {
		return nil
	}
	return m.RelationAttributes
}

func (m *MapEntityConfig) GetTargetSchema() string {
	if m == nil {
		return ""
	}
	return m.TargetSchema
}

func (m *MapEntityConfig) GetTargetUnique() []string {
	if m == nil {
		return nil
	}
	return m.TargetUnique
}
