// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type Mode string

const (
	ModeAppend  Mode = "append"
	ModePrepend Mode = "prepend"
	ModeSet     Mode = "set"
)

func (e Mode) ToPointer() *Mode {
	return &e
}
func (e *Mode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "append":
		fallthrough
	case "prepend":
		fallthrough
	case "set":
		*e = Mode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Mode: %v", v)
	}
}

// SourceFilter - A filter to identify which source entities to pick as relations from main entity
type SourceFilter struct {
	// Filter by a specific relation attribute on the main entity
	Attribute *string `json:"attribute,omitempty"`
	// Limit relations to maximum number (default, all matched relations)
	Limit *int64 `json:"limit,omitempty"`
	// Filter by relation tag (label) on the main entity
	RelationTag *string `json:"relation_tag,omitempty"`
	// Filter by specific schema
	Schema *string `json:"schema,omitempty"`
	// Picks main entity as relation (overrides other filters)
	Self *bool `default:"false" json:"self"`
	// Filter by a specific tag on the related entity
	Tag *string `json:"tag,omitempty"`
}

func (s SourceFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SourceFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SourceFilter) GetAttribute() *string {
	if s == nil {
		return nil
	}
	return s.Attribute
}

func (s *SourceFilter) GetLimit() *int64 {
	if s == nil {
		return nil
	}
	return s.Limit
}

func (s *SourceFilter) GetRelationTag() *string {
	if s == nil {
		return nil
	}
	return s.RelationTag
}

func (s *SourceFilter) GetSchema() *string {
	if s == nil {
		return nil
	}
	return s.Schema
}

func (s *SourceFilter) GetSelf() *bool {
	if s == nil {
		return nil
	}
	return s.Self
}

func (s *SourceFilter) GetTag() *string {
	if s == nil {
		return nil
	}
	return s.Tag
}

type RelationAttribute struct {
	Mode Mode `json:"mode"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	RelatedTo map[string]any `json:"related_to,omitempty"`
	// A filter to identify which source entities to pick as relations from main entity
	SourceFilter *SourceFilter `json:"source_filter,omitempty"`
	// Target attribute to store the relation in
	Target string `json:"target"`
	// Relation tags (labels) to set for the stored relations
	TargetTags []string `json:"target_tags,omitempty"`
	// Include all relation tags (labels) present on the main entity relation
	TargetTagsIncludeSource *bool `default:"false" json:"target_tags_include_source"`
}

func (r RelationAttribute) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RelationAttribute) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RelationAttribute) GetMode() Mode {
	if r == nil {
		return Mode("")
	}
	return r.Mode
}

func (r *RelationAttribute) GetRelatedTo() map[string]any {
	if r == nil {
		return nil
	}
	return r.RelatedTo
}

func (r *RelationAttribute) GetSourceFilter() *SourceFilter {
	if r == nil {
		return nil
	}
	return r.SourceFilter
}

func (r *RelationAttribute) GetTarget() string {
	if r == nil {
		return ""
	}
	return r.Target
}

func (r *RelationAttribute) GetTargetTags() []string {
	if r == nil {
		return nil
	}
	return r.TargetTags
}

func (r *RelationAttribute) GetTargetTagsIncludeSource() *bool {
	if r == nil {
		return nil
	}
	return r.TargetTagsIncludeSource
}
