// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

// LanguageCode - Language code for the email template
type LanguageCode string

const (
	LanguageCodeDe LanguageCode = "de"
	LanguageCodeEn LanguageCode = "en"
)

func (e LanguageCode) ToPointer() *LanguageCode {
	return &e
}
func (e *LanguageCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "de":
		fallthrough
	case "en":
		*e = LanguageCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LanguageCode: %v", v)
	}
}

// ReplyMode - Controls how the reply email is sent.
// - reply_in_thread: Sends the email as a reply within the existing email thread (default).
// - new_email: Sends the email as a new standalone email to the original sender, creating a fresh thread.
type ReplyMode string

const (
	ReplyModeReplyInThread ReplyMode = "reply_in_thread"
	ReplyModeNewEmail      ReplyMode = "new_email"
)

func (e ReplyMode) ToPointer() *ReplyMode {
	return &e
}
func (e *ReplyMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "reply_in_thread":
		fallthrough
	case "new_email":
		*e = ReplyMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReplyMode: %v", v)
	}
}

type ReplyEmailConfig struct {
	// ID of the email template to use for the reply
	EmailTemplateID *string `json:"email_template_id,omitempty"`
	// Language code for the email template
	LanguageCode *LanguageCode `json:"language_code,omitempty"`
	// When enabled, the email thread will be automatically marked as done after this action completes.
	MarkAsDone *bool `default:"false" json:"mark_as_done"`
	// Controls how the reply email is sent.
	// - reply_in_thread: Sends the email as a reply within the existing email thread (default).
	// - new_email: Sends the email as a new standalone email to the original sender, creating a fresh thread.
	//
	ReplyMode *ReplyMode `default:"reply_in_thread" json:"reply_mode"`
}

func (r ReplyEmailConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReplyEmailConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReplyEmailConfig) GetEmailTemplateID() *string {
	if r == nil {
		return nil
	}
	return r.EmailTemplateID
}

func (r *ReplyEmailConfig) GetLanguageCode() *LanguageCode {
	if r == nil {
		return nil
	}
	return r.LanguageCode
}

func (r *ReplyEmailConfig) GetMarkAsDone() *bool {
	if r == nil {
		return nil
	}
	return r.MarkAsDone
}

func (r *ReplyEmailConfig) GetReplyMode() *ReplyMode {
	if r == nil {
		return nil
	}
	return r.ReplyMode
}
