// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ResumeResp struct {
	Execution     AutomationExecution `json:"execution"`
	ResumedAction AnyAction           `json:"resumedAction"`
}

func (r *ResumeResp) GetExecution() AutomationExecution {
	if r == nil {
		return AutomationExecution{}
	}
	return r.Execution
}

func (r *ResumeResp) GetResumedAction() AnyAction {
	if r == nil {
		return AnyAction{}
	}
	return r.ResumedAction
}
