// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ResumeReq struct {
	// A unique token to resume a paused automation execution
	ResumeToken string `json:"resume_token"`
}

func (r *ResumeReq) GetResumeToken() string {
	if r == nil {
		return ""
	}
	return r.ResumeToken
}
