// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ResumeReq struct {
	// A unique token to resume a paused automation execution
	ResumeToken string `json:"resume_token"`
}

func (o *ResumeReq) GetResumeToken() string {
	if o == nil {
		return ""
	}
	return o.ResumeToken
}
