// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ResumeResp struct {
	Execution     AutomationExecution `json:"execution"`
	ResumedAction AnyAction           `json:"resumedAction"`
}

func (o *ResumeResp) GetExecution() AutomationExecution {
	if o == nil {
		return AutomationExecution{}
	}
	return o.Execution
}

func (o *ResumeResp) GetResumedAction() AnyAction {
	if o == nil {
		return AnyAction{}
	}
	return o.ResumedAction
}
