// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SearchAutomationsResp struct {
	Results []AutomationFlow `json:"results"`
	Total   float64          `json:"total"`
}

func (s *SearchAutomationsResp) GetResults() []AutomationFlow {
	if s == nil {
		return []AutomationFlow{}
	}
	return s.Results
}

func (s *SearchAutomationsResp) GetTotal() float64 {
	if s == nil {
		return 0.0
	}
	return s.Total
}
