// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type Equals struct {
	Source *string `json:"source,omitempty"`
	Value  *string `json:"value,omitempty"`
}

func (e Equals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Equals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *Equals) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *Equals) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

type SendEmailCondition struct {
	Equals *Equals `json:"_equals,omitempty"`
}

func (s SendEmailCondition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SendEmailCondition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *SendEmailCondition) GetEquals() *Equals {
	if o == nil {
		return nil
	}
	return o.Equals
}
