// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type StartExecutionRequest struct {
	EntityID *string `json:"entity_id,omitempty"`
}

func (o *StartExecutionRequest) GetEntityID() *string {
	if o == nil {
		return nil
	}
	return o.EntityID
}
