// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type TriggerEventFlowAutomationTaskType string

const (
	TriggerEventFlowAutomationTaskTypeFlowAutomationTask TriggerEventFlowAutomationTaskType = "flow_automation_task"
)

func (e TriggerEventFlowAutomationTaskType) ToPointer() *TriggerEventFlowAutomationTaskType {
	return &e
}
func (e *TriggerEventFlowAutomationTaskType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "flow_automation_task":
		*e = TriggerEventFlowAutomationTaskType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TriggerEventFlowAutomationTaskType: %v", v)
	}
}

type TriggerEventFlowAutomationTask struct {
	Caller               *APICallerContext                   `json:"caller,omitempty"`
	EntityID             string                              `json:"entity_id"`
	FlowAutomationTaskID string                              `json:"flow_automation_task_id"`
	FlowExecutionID      string                              `json:"flow_execution_id"`
	OrgID                string                              `json:"org_id"`
	Type                 *TriggerEventFlowAutomationTaskType `json:"type,omitempty"`
}

func (t TriggerEventFlowAutomationTask) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TriggerEventFlowAutomationTask) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"entity_id", "flow_automation_task_id", "flow_execution_id", "org_id"}); err != nil {
		return err
	}
	return nil
}

func (o *TriggerEventFlowAutomationTask) GetCaller() *APICallerContext {
	if o == nil {
		return nil
	}
	return o.Caller
}

func (o *TriggerEventFlowAutomationTask) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

func (o *TriggerEventFlowAutomationTask) GetFlowAutomationTaskID() string {
	if o == nil {
		return ""
	}
	return o.FlowAutomationTaskID
}

func (o *TriggerEventFlowAutomationTask) GetFlowExecutionID() string {
	if o == nil {
		return ""
	}
	return o.FlowExecutionID
}

func (o *TriggerEventFlowAutomationTask) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}

func (o *TriggerEventFlowAutomationTask) GetType() *TriggerEventFlowAutomationTaskType {
	if o == nil {
		return nil
	}
	return o.Type
}
