// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type TriggerEventManualType string

const (
	TriggerEventManualTypeManual TriggerEventManualType = "manual"
)

func (e TriggerEventManualType) ToPointer() *TriggerEventManualType {
	return &e
}
func (e *TriggerEventManualType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "manual":
		*e = TriggerEventManualType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TriggerEventManualType: %v", v)
	}
}

type TriggerEventManual struct {
	Caller   *APICallerContext       `json:"caller,omitempty"`
	EntityID string                  `json:"entity_id"`
	OrgID    string                  `json:"org_id"`
	Type     *TriggerEventManualType `json:"type,omitempty"`
}

func (t TriggerEventManual) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TriggerEventManual) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TriggerEventManual) GetCaller() *APICallerContext {
	if t == nil {
		return nil
	}
	return t.Caller
}

func (t *TriggerEventManual) GetEntityID() string {
	if t == nil {
		return ""
	}
	return t.EntityID
}

func (t *TriggerEventManual) GetOrgID() string {
	if t == nil {
		return ""
	}
	return t.OrgID
}

func (t *TriggerEventManual) GetType() *TriggerEventManualType {
	if t == nil {
		return nil
	}
	return t.Type
}
