// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TriggerWebhookActionReason struct {
	// Why the action has to be skipped/failed
	Message *string `json:"message,omitempty"`
	// Extra metadata about the skipping reason - such as a certain condition not met, etc.
	Payload map[string]any `json:"payload,omitempty"`
}

func (o *TriggerWebhookActionReason) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *TriggerWebhookActionReason) GetPayload() map[string]any {
	if o == nil {
		return nil
	}
	return o.Payload
}

type TriggerWebhookActionType string

const (
	TriggerWebhookActionTypeTriggerWebhook TriggerWebhookActionType = "trigger-webhook"
)

func (e TriggerWebhookActionType) ToPointer() *TriggerWebhookActionType {
	return &e
}
func (e *TriggerWebhookActionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "trigger-webhook":
		*e = TriggerWebhookActionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TriggerWebhookActionType: %v", v)
	}
}

type TriggerWebhookAction struct {
	// Whether to stop execution in a failed state if this action fails
	AllowFailure *bool `json:"allow_failure,omitempty"`
	// Condition Id to be checked before executing the action
	ConditionID *string               `json:"condition_id,omitempty"`
	Config      *TriggerWebhookConfig `json:"config,omitempty"`
	// Flag indicating whether the action was created automatically or manually
	CreatedAutomatically *bool            `json:"created_automatically,omitempty"`
	ErrorOutput          *ErrorOutput     `json:"error_output,omitempty"`
	ExecutionStatus      *ExecutionStatus `json:"execution_status,omitempty"`
	FlowActionID         *string          `json:"flow_action_id,omitempty"`
	ID                   *string          `json:"id,omitempty"`
	// Flag indicating whether the same action can be in bulk in a single execution. e.g; send-email / map-entity
	IsBulkAction *bool                       `json:"is_bulk_action,omitempty"`
	Name         *string                     `json:"name,omitempty"`
	Outputs      map[string]any              `json:"outputs,omitempty"`
	Reason       *TriggerWebhookActionReason `json:"reason,omitempty"`
	// different behaviors for retrying failed execution actions.
	RetryStrategy *RetryStrategy `json:"retry_strategy,omitempty"`
	// Schedule Id which indicates the schedule of the action
	ScheduleID *string                   `json:"schedule_id,omitempty"`
	StartedAt  *string                   `json:"started_at,omitempty"`
	Type       *TriggerWebhookActionType `json:"type,omitempty"`
	UpdatedAt  *string                   `json:"updated_at,omitempty"`
}

func (o *TriggerWebhookAction) GetAllowFailure() *bool {
	if o == nil {
		return nil
	}
	return o.AllowFailure
}

func (o *TriggerWebhookAction) GetConditionID() *string {
	if o == nil {
		return nil
	}
	return o.ConditionID
}

func (o *TriggerWebhookAction) GetConfig() *TriggerWebhookConfig {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *TriggerWebhookAction) GetCreatedAutomatically() *bool {
	if o == nil {
		return nil
	}
	return o.CreatedAutomatically
}

func (o *TriggerWebhookAction) GetErrorOutput() *ErrorOutput {
	if o == nil {
		return nil
	}
	return o.ErrorOutput
}

func (o *TriggerWebhookAction) GetExecutionStatus() *ExecutionStatus {
	if o == nil {
		return nil
	}
	return o.ExecutionStatus
}

func (o *TriggerWebhookAction) GetFlowActionID() *string {
	if o == nil {
		return nil
	}
	return o.FlowActionID
}

func (o *TriggerWebhookAction) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TriggerWebhookAction) GetIsBulkAction() *bool {
	if o == nil {
		return nil
	}
	return o.IsBulkAction
}

func (o *TriggerWebhookAction) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TriggerWebhookAction) GetOutputs() map[string]any {
	if o == nil {
		return nil
	}
	return o.Outputs
}

func (o *TriggerWebhookAction) GetReason() *TriggerWebhookActionReason {
	if o == nil {
		return nil
	}
	return o.Reason
}

func (o *TriggerWebhookAction) GetRetryStrategy() *RetryStrategy {
	if o == nil {
		return nil
	}
	return o.RetryStrategy
}

func (o *TriggerWebhookAction) GetScheduleID() *string {
	if o == nil {
		return nil
	}
	return o.ScheduleID
}

func (o *TriggerWebhookAction) GetStartedAt() *string {
	if o == nil {
		return nil
	}
	return o.StartedAt
}

func (o *TriggerWebhookAction) GetType() *TriggerWebhookActionType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *TriggerWebhookAction) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
