// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

type TriggerEventActionReason struct {
	// Why the action has to be skipped/failed
	Message *string `json:"message,omitempty"`
	// Extra metadata about the skipping reason - such as a certain condition not met, etc.
	Payload map[string]any `json:"payload,omitempty"`
}

func (t TriggerEventActionReason) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TriggerEventActionReason) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TriggerEventActionReason) GetMessage() *string {
	if t == nil {
		return nil
	}
	return t.Message
}

func (t *TriggerEventActionReason) GetPayload() map[string]any {
	if t == nil {
		return nil
	}
	return t.Payload
}

type TriggerEventActionType string

const (
	TriggerEventActionTypeTriggerEvent TriggerEventActionType = "trigger-event"
)

func (e TriggerEventActionType) ToPointer() *TriggerEventActionType {
	return &e
}
func (e *TriggerEventActionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "trigger-event":
		*e = TriggerEventActionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TriggerEventActionType: %v", v)
	}
}

type TriggerEventAction struct {
	// Whether to stop execution in a failed state if this action fails
	AllowFailure *bool `json:"allow_failure,omitempty"`
	// Condition Id to be checked before executing the action
	ConditionID *string `json:"condition_id,omitempty"`
	// Configuration for triggering an event catalog event
	Config *TriggerEventConfig `json:"config,omitempty"`
	// Flag indicating whether the action was created automatically or manually
	CreatedAutomatically *bool            `json:"created_automatically,omitempty"`
	ErrorOutput          *ErrorOutput     `json:"error_output,omitempty"`
	ExecutionStatus      *ExecutionStatus `json:"execution_status,omitempty"`
	FlowActionID         *string          `json:"flow_action_id,omitempty"`
	ID                   *string          `json:"id,omitempty"`
	// Flag indicating whether the same action can be in bulk in a single execution. e.g; send-email / map-entity
	IsBulkAction *bool `json:"is_bulk_action,omitempty"`
	// For looped actions, an archive of completed iterations. The action's own execution_status / outputs / error_output always reflect the current (latest) iteration. The previous iteration's state is pushed here before the action is reset for the next pass.
	//
	Iterations []AutomationActionIteration `json:"iterations,omitempty"`
	// Id of a loop scope defined on the parent flow. When set, the action runs once per item resolved from the loop's source_path. All actions sharing the same loop_id must be contiguous in the actions array.
	//
	LoopID  *string                   `json:"loop_id,omitempty"`
	Name    *string                   `json:"name,omitempty"`
	Outputs map[string]any            `json:"outputs,omitempty"`
	Reason  *TriggerEventActionReason `json:"reason,omitempty"`
	// different behaviors for retrying failed execution actions.
	RetryStrategy *RetryStrategy `json:"retry_strategy,omitempty"`
	// Schedule Id which indicates the schedule of the action
	ScheduleID *string                 `json:"schedule_id,omitempty"`
	StartedAt  *string                 `json:"started_at,omitempty"`
	Type       *TriggerEventActionType `json:"type,omitempty"`
	UpdatedAt  *string                 `json:"updated_at,omitempty"`
}

func (t TriggerEventAction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TriggerEventAction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TriggerEventAction) GetAllowFailure() *bool {
	if t == nil {
		return nil
	}
	return t.AllowFailure
}

func (t *TriggerEventAction) GetConditionID() *string {
	if t == nil {
		return nil
	}
	return t.ConditionID
}

func (t *TriggerEventAction) GetConfig() *TriggerEventConfig {
	if t == nil {
		return nil
	}
	return t.Config
}

func (t *TriggerEventAction) GetCreatedAutomatically() *bool {
	if t == nil {
		return nil
	}
	return t.CreatedAutomatically
}

func (t *TriggerEventAction) GetErrorOutput() *ErrorOutput {
	if t == nil {
		return nil
	}
	return t.ErrorOutput
}

func (t *TriggerEventAction) GetExecutionStatus() *ExecutionStatus {
	if t == nil {
		return nil
	}
	return t.ExecutionStatus
}

func (t *TriggerEventAction) GetFlowActionID() *string {
	if t == nil {
		return nil
	}
	return t.FlowActionID
}

func (t *TriggerEventAction) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *TriggerEventAction) GetIsBulkAction() *bool {
	if t == nil {
		return nil
	}
	return t.IsBulkAction
}

func (t *TriggerEventAction) GetIterations() []AutomationActionIteration {
	if t == nil {
		return nil
	}
	return t.Iterations
}

func (t *TriggerEventAction) GetLoopID() *string {
	if t == nil {
		return nil
	}
	return t.LoopID
}

func (t *TriggerEventAction) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TriggerEventAction) GetOutputs() map[string]any {
	if t == nil {
		return nil
	}
	return t.Outputs
}

func (t *TriggerEventAction) GetReason() *TriggerEventActionReason {
	if t == nil {
		return nil
	}
	return t.Reason
}

func (t *TriggerEventAction) GetRetryStrategy() *RetryStrategy {
	if t == nil {
		return nil
	}
	return t.RetryStrategy
}

func (t *TriggerEventAction) GetScheduleID() *string {
	if t == nil {
		return nil
	}
	return t.ScheduleID
}

func (t *TriggerEventAction) GetStartedAt() *string {
	if t == nil {
		return nil
	}
	return t.StartedAt
}

func (t *TriggerEventAction) GetType() *TriggerEventActionType {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *TriggerEventAction) GetUpdatedAt() *string {
	if t == nil {
		return nil
	}
	return t.UpdatedAt
}
