// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/internal/utils"
)

// TriggerEventConfig - Configuration for triggering an event catalog event
type TriggerEventConfig struct {
	// Inputs to be passed to trigger the event
	EventInputs map[string]any `json:"event_inputs,omitempty"`
	// The event catalog event name to trigger
	EventName string `json:"event_name"`
}

func (t TriggerEventConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TriggerEventConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TriggerEventConfig) GetEventInputs() map[string]any {
	if t == nil {
		return nil
	}
	return t.EventInputs
}

func (t *TriggerEventConfig) GetEventName() string {
	if t == nil {
		return ""
	}
	return t.EventName
}
