// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type WildcardCondition struct {
	Wildcard *string `json:"wildcard,omitempty"`
}

func (o *WildcardCondition) GetWildcard() *string {
	if o == nil {
		return nil
	}
	return o.Wildcard
}
