// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type WorkflowExecutionContext struct {
	WorkflowExecID     string  `json:"workflow_exec_id"`
	WorkflowExecTaskID *string `json:"workflow_exec_task_id,omitempty"`
	// The role this automation plays in the workflow.
	WorkflowRole WorkflowContextRole `json:"workflow_role"`
}

func (o *WorkflowExecutionContext) GetWorkflowExecID() string {
	if o == nil {
		return ""
	}
	return o.WorkflowExecID
}

func (o *WorkflowExecutionContext) GetWorkflowExecTaskID() *string {
	if o == nil {
		return nil
	}
	return o.WorkflowExecTaskID
}

func (o *WorkflowExecutionContext) GetWorkflowRole() WorkflowContextRole {
	if o == nil {
		return WorkflowContextRole("")
	}
	return o.WorkflowRole
}
