// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/provider/typeconvert"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-automation/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-automation/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *FlowResourceModel) RefreshFromSharedAutomationFlow(ctx context.Context, resp *shared.AutomationFlow) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.Manifest != nil {
			r.Manifest = make([]types.String, 0, len(resp.Manifest))
			for _, v := range resp.Manifest {
				r.Manifest = append(r.Manifest, types.StringValue(v))
			}
		}
		r.Actions = make([]jsontypes.Normalized, 0, len(resp.Actions))
		for _, actionsItem := range resp.Actions {
			var actions jsontypes.Normalized

			actionsResult, _ := json.Marshal(actionsItem)
			actions = jsontypes.NewNormalizedValue(string(actionsResult))

			r.Actions = append(r.Actions, actions)
		}
		r.Conditions = []tfTypes.ActionCondition{}

		for _, conditionsItem := range resp.Conditions {
			var conditions tfTypes.ActionCondition

			conditions.EvaluationResult = types.BoolPointerValue(conditionsItem.EvaluationResult)
			conditions.ID = types.StringPointerValue(conditionsItem.ID)
			conditions.ScheduleID = types.StringPointerValue(conditionsItem.ScheduleID)
			conditions.Statements = []tfTypes.ConditionStatement{}

			for _, statementsItem := range conditionsItem.Statements {
				var statements tfTypes.ConditionStatement

				statements.ID = types.StringPointerValue(statementsItem.ID)
				if statementsItem.Operation != nil {
					statements.Operation = types.StringValue(string(*statementsItem.Operation))
				} else {
					statements.Operation = types.StringNull()
				}
				if statementsItem.Source == nil {
					statements.Source = nil
				} else {
					statements.Source = &tfTypes.Source{}
					statements.Source.Attribute = types.StringPointerValue(statementsItem.Source.Attribute)
					if statementsItem.Source.AttributeOperation != nil {
						statements.Source.AttributeOperation = types.StringValue(string(*statementsItem.Source.AttributeOperation))
					} else {
						statements.Source.AttributeOperation = types.StringNull()
					}
					statements.Source.AttributeRepeatable = types.BoolPointerValue(statementsItem.Source.AttributeRepeatable)
					if statementsItem.Source.AttributeType != nil {
						statements.Source.AttributeType = types.StringValue(string(*statementsItem.Source.AttributeType))
					} else {
						statements.Source.AttributeType = types.StringNull()
					}
					statements.Source.ID = types.StringPointerValue(statementsItem.Source.ID)
					if statementsItem.Source.Origin != nil {
						statements.Source.Origin = types.StringValue(string(*statementsItem.Source.Origin))
					} else {
						statements.Source.Origin = types.StringNull()
					}
					if statementsItem.Source.OriginType != nil {
						statements.Source.OriginType = types.StringValue(string(*statementsItem.Source.OriginType))
					} else {
						statements.Source.OriginType = types.StringNull()
					}
					statements.Source.RepeatableItemOp = types.BoolPointerValue(statementsItem.Source.RepeatableItemOp)
					statements.Source.Schema = types.StringPointerValue(statementsItem.Source.Schema)
				}
				statements.Values = make([]types.String, 0, len(statementsItem.Values))
				for _, v := range statementsItem.Values {
					statements.Values = append(statements.Values, types.StringValue(v))
				}

				conditions.Statements = append(conditions.Statements, statements)
			}

			r.Conditions = append(r.Conditions, conditions)
		}
		if resp.DisableDetails == nil {
			r.DisableDetails = nil
		} else {
			r.DisableDetails = &tfTypes.DisableDetails{}
			r.DisableDetails.Blame = types.StringPointerValue(resp.DisableDetails.Blame)
			r.DisableDetails.DisabledAt = types.StringValue(typeconvert.TimeToString(resp.DisableDetails.DisabledAt))
			r.DisableDetails.DisabledBy = types.StringValue(string(resp.DisableDetails.DisabledBy))
		}
		r.Enabled = types.BoolPointerValue(resp.Enabled)
		r.EntitySchema = types.StringPointerValue(resp.EntitySchema)
		r.FlowName = types.StringValue(resp.FlowName)
		r.ID = types.StringPointerValue(resp.ID)
		if resp.MaxExecutions == nil {
			r.MaxExecutions = nil
		} else {
			r.MaxExecutions = &tfTypes.MaxExecutions{}
			r.MaxExecutions.Count = types.Float64PointerValue(resp.MaxExecutions.Count)
			r.MaxExecutions.Window = types.StringPointerValue(resp.MaxExecutions.Window)
		}
		if resp.Schedules == nil {
			r.Schedules = jsontypes.NewNormalizedNull()
		} else {
			schedulesResult, _ := json.Marshal(resp.Schedules)
			r.Schedules = jsontypes.NewNormalizedValue(string(schedulesResult))
		}
		r.SystemFlow = types.BoolPointerValue(resp.SystemFlow)
		r.TriggerConditions = make([]jsontypes.Normalized, 0, len(resp.TriggerConditions))
		for _, triggerConditionsItem := range resp.TriggerConditions {
			var triggerConditions jsontypes.Normalized

			triggerConditionsResult, _ := json.Marshal(triggerConditionsItem)
			triggerConditions = jsontypes.NewNormalizedValue(string(triggerConditionsResult))

			r.TriggerConditions = append(r.TriggerConditions, triggerConditions)
		}
		r.Triggers = []tfTypes.AnyTrigger{}

		for _, triggersItem := range resp.Triggers {
			var triggers tfTypes.AnyTrigger

			if triggersItem.Any != nil {
				anyResult, _ := json.Marshal(triggersItem.Any)
				triggers.Any = jsontypes.NewNormalizedValue(string(anyResult))
			}
			if triggersItem.APISubmissionTrigger != nil {
				triggers.APISubmissionTrigger = &tfTypes.APISubmissionTrigger{}
				triggers.APISubmissionTrigger.Configuration.SourceID = types.StringPointerValue(triggersItem.APISubmissionTrigger.Configuration.SourceID)
				triggers.APISubmissionTrigger.ID = types.StringPointerValue(triggersItem.APISubmissionTrigger.ID)
				triggers.APISubmissionTrigger.Type = types.StringValue(string(triggersItem.APISubmissionTrigger.Type))
			}
			if triggersItem.EntityManualTrigger != nil {
				triggers.EntityManualTrigger = &tfTypes.EntityManualTrigger{}
				triggers.EntityManualTrigger.Configuration.Schema = types.StringPointerValue(triggersItem.EntityManualTrigger.Configuration.Schema)
				triggers.EntityManualTrigger.ID = types.StringPointerValue(triggersItem.EntityManualTrigger.ID)
				triggers.EntityManualTrigger.Type = types.StringValue(string(triggersItem.EntityManualTrigger.Type))
			}
			if triggersItem.EntityOperationTrigger != nil {
				triggers.EntityOperationTrigger = &tfTypes.EntityOperationTrigger{}
				if triggersItem.EntityOperationTrigger.Configuration.EcpConfig == nil {
					triggers.EntityOperationTrigger.Configuration.EcpConfig = nil
				} else {
					triggers.EntityOperationTrigger.Configuration.EcpConfig = &tfTypes.EcpConfig{}
					if triggersItem.EntityOperationTrigger.Configuration.EcpConfig.FileConfig == nil {
						triggers.EntityOperationTrigger.Configuration.EcpConfig.FileConfig = nil
					} else {
						triggers.EntityOperationTrigger.Configuration.EcpConfig.FileConfig = &tfTypes.FileConfig{}
						triggers.EntityOperationTrigger.Configuration.EcpConfig.FileConfig.SharedWithEndCustomer = types.BoolPointerValue(triggersItem.EntityOperationTrigger.Configuration.EcpConfig.FileConfig.SharedWithEndCustomer)
					}
					triggers.EntityOperationTrigger.Configuration.EcpConfig.Origin = types.StringPointerValue(triggersItem.EntityOperationTrigger.Configuration.EcpConfig.Origin)
					triggers.EntityOperationTrigger.Configuration.EcpConfig.PortalID = types.StringPointerValue(triggersItem.EntityOperationTrigger.Configuration.EcpConfig.PortalID)
				}
				triggers.EntityOperationTrigger.Configuration.ExcludeActivities = make([]types.String, 0, len(triggersItem.EntityOperationTrigger.Configuration.ExcludeActivities))
				for _, v := range triggersItem.EntityOperationTrigger.Configuration.ExcludeActivities {
					triggers.EntityOperationTrigger.Configuration.ExcludeActivities = append(triggers.EntityOperationTrigger.Configuration.ExcludeActivities, types.StringValue(v))
				}
				if triggersItem.EntityOperationTrigger.Configuration.FilterConfig == nil {
					triggers.EntityOperationTrigger.Configuration.FilterConfig = nil
				} else {
					triggers.EntityOperationTrigger.Configuration.FilterConfig = &tfTypes.FilterConfig{}
					if triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Activity == nil {
						triggers.EntityOperationTrigger.Configuration.FilterConfig.Activity = nil
					} else {
						triggers.EntityOperationTrigger.Configuration.FilterConfig.Activity = &tfTypes.Activity{}
						triggers.EntityOperationTrigger.Configuration.FilterConfig.Activity.Type = []tfTypes.EntityOperationTriggerSchemasType{}

						for _, typeVarItem := range triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Activity.Type {
							var typeVar tfTypes.EntityOperationTriggerSchemasType

							if typeVarItem.Str != nil {
								typeVar.Str = types.StringPointerValue(typeVarItem.Str)
							}
							if typeVarItem.AnythingButCondition != nil {
								typeVar.AnythingButCondition = &tfTypes.AnythingButCondition{}
								typeVar.AnythingButCondition.AnythingBut = make([]types.String, 0, len(typeVarItem.AnythingButCondition.AnythingBut))
								for _, v := range typeVarItem.AnythingButCondition.AnythingBut {
									typeVar.AnythingButCondition.AnythingBut = append(typeVar.AnythingButCondition.AnythingBut, types.StringValue(v))
								}
							}
							if typeVarItem.EqualsIgnoreCaseCondition != nil {
								typeVar.EqualsIgnoreCaseCondition = &tfTypes.EqualsIgnoreCaseCondition{}
								typeVar.EqualsIgnoreCaseCondition.EqualsIgnoreCase = types.StringPointerValue(typeVarItem.EqualsIgnoreCaseCondition.EqualsIgnoreCase)
							}
							if typeVarItem.ExistsCondition != nil {
								typeVar.ExistsCondition = &tfTypes.ExistsCondition{}
								typeVar.ExistsCondition.Exists = types.BoolPointerValue(typeVarItem.ExistsCondition.Exists)
							}
							if typeVarItem.PrefixCondition != nil {
								typeVar.PrefixCondition = &tfTypes.PrefixCondition{}
								typeVar.PrefixCondition.Prefix = types.StringPointerValue(typeVarItem.PrefixCondition.Prefix)
							}
							if typeVarItem.SuffixCondition != nil {
								typeVar.SuffixCondition = &tfTypes.SuffixCondition{}
								typeVar.SuffixCondition.Suffix = types.StringPointerValue(typeVarItem.SuffixCondition.Suffix)
							}
							if typeVarItem.WildcardCondition != nil {
								typeVar.WildcardCondition = &tfTypes.WildcardCondition{}
								typeVar.WildcardCondition.Wildcard = types.StringPointerValue(typeVarItem.WildcardCondition.Wildcard)
							}

							triggers.EntityOperationTrigger.Configuration.FilterConfig.Activity.Type = append(triggers.EntityOperationTrigger.Configuration.FilterConfig.Activity.Type, typeVar)
						}
					}
					if triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation == nil {
						triggers.EntityOperationTrigger.Configuration.FilterConfig.Operation = nil
					} else {
						triggers.EntityOperationTrigger.Configuration.FilterConfig.Operation = &tfTypes.EntityOperationTriggerOperation{}
						if triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Diff == nil {
							triggers.EntityOperationTrigger.Configuration.FilterConfig.Operation.Diff = jsontypes.NewNormalizedNull()
						} else {
							diffResult, _ := json.Marshal(triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Diff)
							triggers.EntityOperationTrigger.Configuration.FilterConfig.Operation.Diff = jsontypes.NewNormalizedValue(string(diffResult))
						}
						triggers.EntityOperationTrigger.Configuration.FilterConfig.Operation.Operation = make([]types.String, 0, len(triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Operation))
						for _, v := range triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Operation {
							triggers.EntityOperationTrigger.Configuration.FilterConfig.Operation.Operation = append(triggers.EntityOperationTrigger.Configuration.FilterConfig.Operation.Operation, types.StringValue(string(v)))
						}
						if triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Payload == nil {
							triggers.EntityOperationTrigger.Configuration.FilterConfig.Operation.Payload = jsontypes.NewNormalizedNull()
						} else {
							payloadResult, _ := json.Marshal(triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Payload)
							triggers.EntityOperationTrigger.Configuration.FilterConfig.Operation.Payload = jsontypes.NewNormalizedValue(string(payloadResult))
						}
					}
				}
				triggers.EntityOperationTrigger.Configuration.IncludeActivities = make([]types.String, 0, len(triggersItem.EntityOperationTrigger.Configuration.IncludeActivities))
				for _, v := range triggersItem.EntityOperationTrigger.Configuration.IncludeActivities {
					triggers.EntityOperationTrigger.Configuration.IncludeActivities = append(triggers.EntityOperationTrigger.Configuration.IncludeActivities, types.StringValue(v))
				}
				triggers.EntityOperationTrigger.Configuration.Operations = make([]types.String, 0, len(triggersItem.EntityOperationTrigger.Configuration.Operations))
				for _, v := range triggersItem.EntityOperationTrigger.Configuration.Operations {
					triggers.EntityOperationTrigger.Configuration.Operations = append(triggers.EntityOperationTrigger.Configuration.Operations, types.StringValue(string(v)))
				}
				triggers.EntityOperationTrigger.Configuration.Schema = types.StringPointerValue(triggersItem.EntityOperationTrigger.Configuration.Schema)
				triggers.EntityOperationTrigger.ID = types.StringPointerValue(triggersItem.EntityOperationTrigger.ID)
				triggers.EntityOperationTrigger.Type = types.StringValue(string(triggersItem.EntityOperationTrigger.Type))
			}
			if triggersItem.FlowsTrigger != nil {
				triggers.FlowsTrigger = &tfTypes.FlowsTrigger{}
				triggers.FlowsTrigger.Configuration.JourneyID = types.StringPointerValue(triggersItem.FlowsTrigger.Configuration.JourneyID)
				triggers.FlowsTrigger.Configuration.SourceID = types.StringValue(triggersItem.FlowsTrigger.Configuration.SourceID)
				triggers.FlowsTrigger.ID = types.StringPointerValue(triggersItem.FlowsTrigger.ID)
				triggers.FlowsTrigger.Type = types.StringValue(string(triggersItem.FlowsTrigger.Type))
			}
			if triggersItem.FrontendSubmitTrigger != nil {
				triggers.FrontendSubmitTrigger = &tfTypes.APISubmissionTrigger{}
				triggers.FrontendSubmitTrigger.Configuration.SourceID = types.StringPointerValue(triggersItem.FrontendSubmitTrigger.Configuration.SourceID)
				triggers.FrontendSubmitTrigger.ID = types.StringPointerValue(triggersItem.FrontendSubmitTrigger.ID)
				triggers.FrontendSubmitTrigger.Type = types.StringValue(string(triggersItem.FrontendSubmitTrigger.Type))
			}
			if triggersItem.JourneySubmitTrigger != nil {
				triggers.JourneySubmitTrigger = &tfTypes.JourneySubmitTrigger{}
				triggers.JourneySubmitTrigger.Configuration.SourceID = types.StringValue(triggersItem.JourneySubmitTrigger.Configuration.SourceID)
				triggers.JourneySubmitTrigger.ID = types.StringPointerValue(triggersItem.JourneySubmitTrigger.ID)
				triggers.JourneySubmitTrigger.Type = types.StringValue(string(triggersItem.JourneySubmitTrigger.Type))
			}
			if triggersItem.ReceivedEmailTrigger != nil {
				triggers.ReceivedEmailTrigger = &tfTypes.ReceivedEmailTrigger{}
				if triggersItem.ReceivedEmailTrigger.Configuration.MessageType != nil {
					triggers.ReceivedEmailTrigger.Configuration.MessageType = types.StringValue(string(*triggersItem.ReceivedEmailTrigger.Configuration.MessageType))
				} else {
					triggers.ReceivedEmailTrigger.Configuration.MessageType = types.StringNull()
				}
				triggers.ReceivedEmailTrigger.ID = types.StringPointerValue(triggersItem.ReceivedEmailTrigger.ID)
				triggers.ReceivedEmailTrigger.Type = types.StringValue(string(triggersItem.ReceivedEmailTrigger.Type))
			}

			r.Triggers = append(r.Triggers, triggers)
		}
		r.Version = types.Float64PointerValue(resp.Version)
		if resp.WorkflowContext == nil {
			r.WorkflowContext = nil
		} else {
			r.WorkflowContext = &tfTypes.WorkflowContext{}
			r.WorkflowContext.TaskID = types.StringPointerValue(resp.WorkflowContext.TaskID)
			r.WorkflowContext.WorkflowID = types.StringValue(resp.WorkflowContext.WorkflowID)
			r.WorkflowContext.WorkflowRole = types.StringValue(string(resp.WorkflowContext.WorkflowRole))
		}
	}

	return diags
}

func (r *FlowResourceModel) ToOperationsDeleteFlowRequest(ctx context.Context) (*operations.DeleteFlowRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var flowID string
	flowID = r.ID.ValueString()

	out := operations.DeleteFlowRequest{
		FlowID: flowID,
	}

	return &out, diags
}

func (r *FlowResourceModel) ToOperationsGetFlowRequest(ctx context.Context) (*operations.GetFlowRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var flowID string
	flowID = r.ID.ValueString()

	out := operations.GetFlowRequest{
		FlowID: flowID,
	}

	return &out, diags
}

func (r *FlowResourceModel) ToOperationsPutFlowRequest(ctx context.Context) (*operations.PutFlowRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	automationFlow, automationFlowDiags := r.ToSharedAutomationFlowInput(ctx)
	diags.Append(automationFlowDiags...)

	if diags.HasError() {
		return nil, diags
	}

	var flowID string
	flowID = r.ID.ValueString()

	out := operations.PutFlowRequest{
		AutomationFlow: automationFlow,
		FlowID:         flowID,
	}

	return &out, diags
}

func (r *FlowResourceModel) ToSharedAutomationFlowInput(ctx context.Context) (*shared.AutomationFlowInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	var manifest []string
	if r.Manifest != nil {
		manifest = make([]string, 0, len(r.Manifest))
		for _, manifestItem := range r.Manifest {
			manifest = append(manifest, manifestItem.ValueString())
		}
	}
	actions := make([]interface{}, 0, len(r.Actions))
	for _, actionsItem := range r.Actions {
		var actionsTmp interface{}
		_ = json.Unmarshal([]byte(actionsItem.ValueString()), &actionsTmp)
		actions = append(actions, actionsTmp)
	}
	conditions := make([]shared.ActionCondition, 0, len(r.Conditions))
	for _, conditionsItem := range r.Conditions {
		evaluationResult := new(bool)
		if !conditionsItem.EvaluationResult.IsUnknown() && !conditionsItem.EvaluationResult.IsNull() {
			*evaluationResult = conditionsItem.EvaluationResult.ValueBool()
		} else {
			evaluationResult = nil
		}
		id := new(string)
		if !conditionsItem.ID.IsUnknown() && !conditionsItem.ID.IsNull() {
			*id = conditionsItem.ID.ValueString()
		} else {
			id = nil
		}
		scheduleID := new(string)
		if !conditionsItem.ScheduleID.IsUnknown() && !conditionsItem.ScheduleID.IsNull() {
			*scheduleID = conditionsItem.ScheduleID.ValueString()
		} else {
			scheduleID = nil
		}
		statements := make([]shared.ConditionStatement, 0, len(conditionsItem.Statements))
		for _, statementsItem := range conditionsItem.Statements {
			id1 := new(string)
			if !statementsItem.ID.IsUnknown() && !statementsItem.ID.IsNull() {
				*id1 = statementsItem.ID.ValueString()
			} else {
				id1 = nil
			}
			operation := new(shared.Operation)
			if !statementsItem.Operation.IsUnknown() && !statementsItem.Operation.IsNull() {
				*operation = shared.Operation(statementsItem.Operation.ValueString())
			} else {
				operation = nil
			}
			var source *shared.Source
			if statementsItem.Source != nil {
				attribute := new(string)
				if !statementsItem.Source.Attribute.IsUnknown() && !statementsItem.Source.Attribute.IsNull() {
					*attribute = statementsItem.Source.Attribute.ValueString()
				} else {
					attribute = nil
				}
				attributeOperation := new(shared.AttributeOperation)
				if !statementsItem.Source.AttributeOperation.IsUnknown() && !statementsItem.Source.AttributeOperation.IsNull() {
					*attributeOperation = shared.AttributeOperation(statementsItem.Source.AttributeOperation.ValueString())
				} else {
					attributeOperation = nil
				}
				attributeRepeatable := new(bool)
				if !statementsItem.Source.AttributeRepeatable.IsUnknown() && !statementsItem.Source.AttributeRepeatable.IsNull() {
					*attributeRepeatable = statementsItem.Source.AttributeRepeatable.ValueBool()
				} else {
					attributeRepeatable = nil
				}
				attributeType := new(shared.AttributeType)
				if !statementsItem.Source.AttributeType.IsUnknown() && !statementsItem.Source.AttributeType.IsNull() {
					*attributeType = shared.AttributeType(statementsItem.Source.AttributeType.ValueString())
				} else {
					attributeType = nil
				}
				id2 := new(string)
				if !statementsItem.Source.ID.IsUnknown() && !statementsItem.Source.ID.IsNull() {
					*id2 = statementsItem.Source.ID.ValueString()
				} else {
					id2 = nil
				}
				origin := new(shared.ConditionStatementOrigin)
				if !statementsItem.Source.Origin.IsUnknown() && !statementsItem.Source.Origin.IsNull() {
					*origin = shared.ConditionStatementOrigin(statementsItem.Source.Origin.ValueString())
				} else {
					origin = nil
				}
				originType := new(shared.OriginType)
				if !statementsItem.Source.OriginType.IsUnknown() && !statementsItem.Source.OriginType.IsNull() {
					*originType = shared.OriginType(statementsItem.Source.OriginType.ValueString())
				} else {
					originType = nil
				}
				repeatableItemOp := new(bool)
				if !statementsItem.Source.RepeatableItemOp.IsUnknown() && !statementsItem.Source.RepeatableItemOp.IsNull() {
					*repeatableItemOp = statementsItem.Source.RepeatableItemOp.ValueBool()
				} else {
					repeatableItemOp = nil
				}
				schema := new(string)
				if !statementsItem.Source.Schema.IsUnknown() && !statementsItem.Source.Schema.IsNull() {
					*schema = statementsItem.Source.Schema.ValueString()
				} else {
					schema = nil
				}
				source = &shared.Source{
					Attribute:           attribute,
					AttributeOperation:  attributeOperation,
					AttributeRepeatable: attributeRepeatable,
					AttributeType:       attributeType,
					ID:                  id2,
					Origin:              origin,
					OriginType:          originType,
					RepeatableItemOp:    repeatableItemOp,
					Schema:              schema,
				}
			}
			values := make([]string, 0, len(statementsItem.Values))
			for _, valuesItem := range statementsItem.Values {
				values = append(values, valuesItem.ValueString())
			}
			statements = append(statements, shared.ConditionStatement{
				ID:        id1,
				Operation: operation,
				Source:    source,
				Values:    values,
			})
		}
		conditions = append(conditions, shared.ActionCondition{
			EvaluationResult: evaluationResult,
			ID:               id,
			ScheduleID:       scheduleID,
			Statements:       statements,
		})
	}
	var disableDetails *shared.DisableDetails
	if r.DisableDetails != nil {
		blame := new(string)
		if !r.DisableDetails.Blame.IsUnknown() && !r.DisableDetails.Blame.IsNull() {
			*blame = r.DisableDetails.Blame.ValueString()
		} else {
			blame = nil
		}
		disabledAt, _ := time.Parse(time.RFC3339Nano, r.DisableDetails.DisabledAt.ValueString())
		disabledBy := shared.DisabledBy(r.DisableDetails.DisabledBy.ValueString())
		disableDetails = &shared.DisableDetails{
			Blame:      blame,
			DisabledAt: disabledAt,
			DisabledBy: disabledBy,
		}
	}
	enabled := new(bool)
	if !r.Enabled.IsUnknown() && !r.Enabled.IsNull() {
		*enabled = r.Enabled.ValueBool()
	} else {
		enabled = nil
	}
	entitySchema := new(string)
	if !r.EntitySchema.IsUnknown() && !r.EntitySchema.IsNull() {
		*entitySchema = r.EntitySchema.ValueString()
	} else {
		entitySchema = nil
	}
	var flowName string
	flowName = r.FlowName.ValueString()

	var maxExecutions *shared.MaxExecutions
	if r.MaxExecutions != nil {
		count := new(float64)
		if !r.MaxExecutions.Count.IsUnknown() && !r.MaxExecutions.Count.IsNull() {
			*count = r.MaxExecutions.Count.ValueFloat64()
		} else {
			count = nil
		}
		window := new(string)
		if !r.MaxExecutions.Window.IsUnknown() && !r.MaxExecutions.Window.IsNull() {
			*window = r.MaxExecutions.Window.ValueString()
		} else {
			window = nil
		}
		maxExecutions = &shared.MaxExecutions{
			Count:  count,
			Window: window,
		}
	}
	var schedules interface{}
	if !r.Schedules.IsUnknown() && !r.Schedules.IsNull() {
		_ = json.Unmarshal([]byte(r.Schedules.ValueString()), &schedules)
	}
	systemFlow := new(bool)
	if !r.SystemFlow.IsUnknown() && !r.SystemFlow.IsNull() {
		*systemFlow = r.SystemFlow.ValueBool()
	} else {
		systemFlow = nil
	}
	triggerConditions := make([]interface{}, 0, len(r.TriggerConditions))
	for _, triggerConditionsItem := range r.TriggerConditions {
		var triggerConditionsTmp interface{}
		_ = json.Unmarshal([]byte(triggerConditionsItem.ValueString()), &triggerConditionsTmp)
		triggerConditions = append(triggerConditions, triggerConditionsTmp)
	}
	triggers := make([]shared.AnyTrigger, 0, len(r.Triggers))
	for _, triggersItem := range r.Triggers {
		if triggersItem.FrontendSubmitTrigger != nil {
			sourceID := new(string)
			if !triggersItem.FrontendSubmitTrigger.Configuration.SourceID.IsUnknown() && !triggersItem.FrontendSubmitTrigger.Configuration.SourceID.IsNull() {
				*sourceID = triggersItem.FrontendSubmitTrigger.Configuration.SourceID.ValueString()
			} else {
				sourceID = nil
			}
			configuration := shared.FrontendSubmitTriggerConfiguration{
				SourceID: sourceID,
			}
			id3 := new(string)
			if !triggersItem.FrontendSubmitTrigger.ID.IsUnknown() && !triggersItem.FrontendSubmitTrigger.ID.IsNull() {
				*id3 = triggersItem.FrontendSubmitTrigger.ID.ValueString()
			} else {
				id3 = nil
			}
			typeVar := shared.FrontendSubmitTriggerType(triggersItem.FrontendSubmitTrigger.Type.ValueString())
			frontendSubmitTrigger := shared.FrontendSubmitTrigger{
				Configuration: configuration,
				ID:            id3,
				Type:          typeVar,
			}
			triggers = append(triggers, shared.AnyTrigger{
				FrontendSubmitTrigger: &frontendSubmitTrigger,
			})
		}
		if triggersItem.JourneySubmitTrigger != nil {
			var sourceId1 string
			sourceId1 = triggersItem.JourneySubmitTrigger.Configuration.SourceID.ValueString()

			configuration1 := shared.JourneySubmitTriggerConfiguration{
				SourceID: sourceId1,
			}
			id4 := new(string)
			if !triggersItem.JourneySubmitTrigger.ID.IsUnknown() && !triggersItem.JourneySubmitTrigger.ID.IsNull() {
				*id4 = triggersItem.JourneySubmitTrigger.ID.ValueString()
			} else {
				id4 = nil
			}
			typeVar1 := shared.JourneySubmitTriggerType(triggersItem.JourneySubmitTrigger.Type.ValueString())
			journeySubmitTrigger := shared.JourneySubmitTrigger{
				Configuration: configuration1,
				ID:            id4,
				Type:          typeVar1,
			}
			triggers = append(triggers, shared.AnyTrigger{
				JourneySubmitTrigger: &journeySubmitTrigger,
			})
		}
		if triggersItem.APISubmissionTrigger != nil {
			sourceId2 := new(string)
			if !triggersItem.APISubmissionTrigger.Configuration.SourceID.IsUnknown() && !triggersItem.APISubmissionTrigger.Configuration.SourceID.IsNull() {
				*sourceId2 = triggersItem.APISubmissionTrigger.Configuration.SourceID.ValueString()
			} else {
				sourceId2 = nil
			}
			configuration2 := shared.Configuration{
				SourceID: sourceId2,
			}
			id5 := new(string)
			if !triggersItem.APISubmissionTrigger.ID.IsUnknown() && !triggersItem.APISubmissionTrigger.ID.IsNull() {
				*id5 = triggersItem.APISubmissionTrigger.ID.ValueString()
			} else {
				id5 = nil
			}
			typeVar2 := shared.Type(triggersItem.APISubmissionTrigger.Type.ValueString())
			apiSubmissionTrigger := shared.APISubmissionTrigger{
				Configuration: configuration2,
				ID:            id5,
				Type:          typeVar2,
			}
			triggers = append(triggers, shared.AnyTrigger{
				APISubmissionTrigger: &apiSubmissionTrigger,
			})
		}
		if triggersItem.EntityOperationTrigger != nil {
			var ecpConfig *shared.EcpConfig
			if triggersItem.EntityOperationTrigger.Configuration.EcpConfig != nil {
				var fileConfig *shared.FileConfig
				if triggersItem.EntityOperationTrigger.Configuration.EcpConfig.FileConfig != nil {
					sharedWithEndCustomer := new(bool)
					if !triggersItem.EntityOperationTrigger.Configuration.EcpConfig.FileConfig.SharedWithEndCustomer.IsUnknown() && !triggersItem.EntityOperationTrigger.Configuration.EcpConfig.FileConfig.SharedWithEndCustomer.IsNull() {
						*sharedWithEndCustomer = triggersItem.EntityOperationTrigger.Configuration.EcpConfig.FileConfig.SharedWithEndCustomer.ValueBool()
					} else {
						sharedWithEndCustomer = nil
					}
					fileConfig = &shared.FileConfig{
						SharedWithEndCustomer: sharedWithEndCustomer,
					}
				}
				origin1 := new(string)
				if !triggersItem.EntityOperationTrigger.Configuration.EcpConfig.Origin.IsUnknown() && !triggersItem.EntityOperationTrigger.Configuration.EcpConfig.Origin.IsNull() {
					*origin1 = triggersItem.EntityOperationTrigger.Configuration.EcpConfig.Origin.ValueString()
				} else {
					origin1 = nil
				}
				portalID := new(string)
				if !triggersItem.EntityOperationTrigger.Configuration.EcpConfig.PortalID.IsUnknown() && !triggersItem.EntityOperationTrigger.Configuration.EcpConfig.PortalID.IsNull() {
					*portalID = triggersItem.EntityOperationTrigger.Configuration.EcpConfig.PortalID.ValueString()
				} else {
					portalID = nil
				}
				ecpConfig = &shared.EcpConfig{
					FileConfig: fileConfig,
					Origin:     origin1,
					PortalID:   portalID,
				}
			}
			excludeActivities := make([]string, 0, len(triggersItem.EntityOperationTrigger.Configuration.ExcludeActivities))
			for _, excludeActivitiesItem := range triggersItem.EntityOperationTrigger.Configuration.ExcludeActivities {
				excludeActivities = append(excludeActivities, excludeActivitiesItem.ValueString())
			}
			var filterConfig *shared.FilterConfig
			if triggersItem.EntityOperationTrigger.Configuration.FilterConfig != nil {
				var activity *shared.Activity
				if triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Activity != nil {
					typeVar3 := make([]shared.EntityOperationTriggerSchemasType, 0, len(triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Activity.Type))
					for _, typeItem := range triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Activity.Type {
						if !typeItem.Str.IsUnknown() && !typeItem.Str.IsNull() {
							var str string
							str = typeItem.Str.ValueString()

							typeVar3 = append(typeVar3, shared.EntityOperationTriggerSchemasType{
								Str: &str,
							})
						}
						if typeItem.EqualsIgnoreCaseCondition != nil {
							equalsIgnoreCase := new(string)
							if !typeItem.EqualsIgnoreCaseCondition.EqualsIgnoreCase.IsUnknown() && !typeItem.EqualsIgnoreCaseCondition.EqualsIgnoreCase.IsNull() {
								*equalsIgnoreCase = typeItem.EqualsIgnoreCaseCondition.EqualsIgnoreCase.ValueString()
							} else {
								equalsIgnoreCase = nil
							}
							equalsIgnoreCaseCondition := shared.EqualsIgnoreCaseCondition{
								EqualsIgnoreCase: equalsIgnoreCase,
							}
							typeVar3 = append(typeVar3, shared.EntityOperationTriggerSchemasType{
								EqualsIgnoreCaseCondition: &equalsIgnoreCaseCondition,
							})
						}
						if typeItem.AnythingButCondition != nil {
							anythingBut := make([]string, 0, len(typeItem.AnythingButCondition.AnythingBut))
							for _, anythingButItem := range typeItem.AnythingButCondition.AnythingBut {
								anythingBut = append(anythingBut, anythingButItem.ValueString())
							}
							anythingButCondition := shared.AnythingButCondition{
								AnythingBut: anythingBut,
							}
							typeVar3 = append(typeVar3, shared.EntityOperationTriggerSchemasType{
								AnythingButCondition: &anythingButCondition,
							})
						}
						if typeItem.ExistsCondition != nil {
							exists := new(bool)
							if !typeItem.ExistsCondition.Exists.IsUnknown() && !typeItem.ExistsCondition.Exists.IsNull() {
								*exists = typeItem.ExistsCondition.Exists.ValueBool()
							} else {
								exists = nil
							}
							existsCondition := shared.ExistsCondition{
								Exists: exists,
							}
							typeVar3 = append(typeVar3, shared.EntityOperationTriggerSchemasType{
								ExistsCondition: &existsCondition,
							})
						}
						if typeItem.PrefixCondition != nil {
							prefix := new(string)
							if !typeItem.PrefixCondition.Prefix.IsUnknown() && !typeItem.PrefixCondition.Prefix.IsNull() {
								*prefix = typeItem.PrefixCondition.Prefix.ValueString()
							} else {
								prefix = nil
							}
							prefixCondition := shared.PrefixCondition{
								Prefix: prefix,
							}
							typeVar3 = append(typeVar3, shared.EntityOperationTriggerSchemasType{
								PrefixCondition: &prefixCondition,
							})
						}
						if typeItem.SuffixCondition != nil {
							suffix := new(string)
							if !typeItem.SuffixCondition.Suffix.IsUnknown() && !typeItem.SuffixCondition.Suffix.IsNull() {
								*suffix = typeItem.SuffixCondition.Suffix.ValueString()
							} else {
								suffix = nil
							}
							suffixCondition := shared.SuffixCondition{
								Suffix: suffix,
							}
							typeVar3 = append(typeVar3, shared.EntityOperationTriggerSchemasType{
								SuffixCondition: &suffixCondition,
							})
						}
						if typeItem.WildcardCondition != nil {
							wildcard := new(string)
							if !typeItem.WildcardCondition.Wildcard.IsUnknown() && !typeItem.WildcardCondition.Wildcard.IsNull() {
								*wildcard = typeItem.WildcardCondition.Wildcard.ValueString()
							} else {
								wildcard = nil
							}
							wildcardCondition := shared.WildcardCondition{
								Wildcard: wildcard,
							}
							typeVar3 = append(typeVar3, shared.EntityOperationTriggerSchemasType{
								WildcardCondition: &wildcardCondition,
							})
						}
					}
					activity = &shared.Activity{
						Type: typeVar3,
					}
				}
				var operation1 *shared.EntityOperationTriggerOperation
				if triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation != nil {
					var diff interface{}
					if !triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Diff.IsUnknown() && !triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Diff.IsNull() {
						_ = json.Unmarshal([]byte(triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Diff.ValueString()), &diff)
					}
					operation2 := make([]shared.EntityOperation, 0, len(triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Operation))
					for _, operationItem := range triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Operation {
						operation2 = append(operation2, shared.EntityOperation(operationItem.ValueString()))
					}
					var payload interface{}
					if !triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Payload.IsUnknown() && !triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Payload.IsNull() {
						_ = json.Unmarshal([]byte(triggersItem.EntityOperationTrigger.Configuration.FilterConfig.Operation.Payload.ValueString()), &payload)
					}
					operation1 = &shared.EntityOperationTriggerOperation{
						Diff:      diff,
						Operation: operation2,
						Payload:   payload,
					}
				}
				filterConfig = &shared.FilterConfig{
					Activity:  activity,
					Operation: operation1,
				}
			}
			includeActivities := make([]string, 0, len(triggersItem.EntityOperationTrigger.Configuration.IncludeActivities))
			for _, includeActivitiesItem := range triggersItem.EntityOperationTrigger.Configuration.IncludeActivities {
				includeActivities = append(includeActivities, includeActivitiesItem.ValueString())
			}
			operationsVar := make([]shared.EntityOperation, 0, len(triggersItem.EntityOperationTrigger.Configuration.Operations))
			for _, operationsItem := range triggersItem.EntityOperationTrigger.Configuration.Operations {
				operationsVar = append(operationsVar, shared.EntityOperation(operationsItem.ValueString()))
			}
			schema1 := new(string)
			if !triggersItem.EntityOperationTrigger.Configuration.Schema.IsUnknown() && !triggersItem.EntityOperationTrigger.Configuration.Schema.IsNull() {
				*schema1 = triggersItem.EntityOperationTrigger.Configuration.Schema.ValueString()
			} else {
				schema1 = nil
			}
			configuration3 := shared.EntityOperationTriggerConfiguration{
				EcpConfig:         ecpConfig,
				ExcludeActivities: excludeActivities,
				FilterConfig:      filterConfig,
				IncludeActivities: includeActivities,
				Operations:        operationsVar,
				Schema:            schema1,
			}
			id6 := new(string)
			if !triggersItem.EntityOperationTrigger.ID.IsUnknown() && !triggersItem.EntityOperationTrigger.ID.IsNull() {
				*id6 = triggersItem.EntityOperationTrigger.ID.ValueString()
			} else {
				id6 = nil
			}
			typeVar4 := shared.EntityOperationTriggerType(triggersItem.EntityOperationTrigger.Type.ValueString())
			entityOperationTrigger := shared.EntityOperationTrigger{
				Configuration: configuration3,
				ID:            id6,
				Type:          typeVar4,
			}
			triggers = append(triggers, shared.AnyTrigger{
				EntityOperationTrigger: &entityOperationTrigger,
			})
		}
		if !triggersItem.Any.IsUnknown() && !triggersItem.Any.IsNull() {
			var anyVar interface{}
			_ = json.Unmarshal([]byte(triggersItem.Any.ValueString()), &anyVar)
			triggers = append(triggers, shared.AnyTrigger{
				Any: &anyVar,
			})
		}
		if triggersItem.EntityManualTrigger != nil {
			schema2 := new(string)
			if !triggersItem.EntityManualTrigger.Configuration.Schema.IsUnknown() && !triggersItem.EntityManualTrigger.Configuration.Schema.IsNull() {
				*schema2 = triggersItem.EntityManualTrigger.Configuration.Schema.ValueString()
			} else {
				schema2 = nil
			}
			configuration4 := shared.EntityManualTriggerConfiguration{
				Schema: schema2,
			}
			id7 := new(string)
			if !triggersItem.EntityManualTrigger.ID.IsUnknown() && !triggersItem.EntityManualTrigger.ID.IsNull() {
				*id7 = triggersItem.EntityManualTrigger.ID.ValueString()
			} else {
				id7 = nil
			}
			typeVar5 := shared.EntityManualTriggerType(triggersItem.EntityManualTrigger.Type.ValueString())
			entityManualTrigger := shared.EntityManualTrigger{
				Configuration: configuration4,
				ID:            id7,
				Type:          typeVar5,
			}
			triggers = append(triggers, shared.AnyTrigger{
				EntityManualTrigger: &entityManualTrigger,
			})
		}
		if triggersItem.ReceivedEmailTrigger != nil {
			messageType := new(shared.MessageType)
			if !triggersItem.ReceivedEmailTrigger.Configuration.MessageType.IsUnknown() && !triggersItem.ReceivedEmailTrigger.Configuration.MessageType.IsNull() {
				*messageType = shared.MessageType(triggersItem.ReceivedEmailTrigger.Configuration.MessageType.ValueString())
			} else {
				messageType = nil
			}
			configuration5 := shared.ReceivedEmailTriggerConfiguration{
				MessageType: messageType,
			}
			id8 := new(string)
			if !triggersItem.ReceivedEmailTrigger.ID.IsUnknown() && !triggersItem.ReceivedEmailTrigger.ID.IsNull() {
				*id8 = triggersItem.ReceivedEmailTrigger.ID.ValueString()
			} else {
				id8 = nil
			}
			typeVar6 := shared.ReceivedEmailTriggerType(triggersItem.ReceivedEmailTrigger.Type.ValueString())
			receivedEmailTrigger := shared.ReceivedEmailTrigger{
				Configuration: configuration5,
				ID:            id8,
				Type:          typeVar6,
			}
			triggers = append(triggers, shared.AnyTrigger{
				ReceivedEmailTrigger: &receivedEmailTrigger,
			})
		}
		if triggersItem.FlowsTrigger != nil {
			journeyID := new(string)
			if !triggersItem.FlowsTrigger.Configuration.JourneyID.IsUnknown() && !triggersItem.FlowsTrigger.Configuration.JourneyID.IsNull() {
				*journeyID = triggersItem.FlowsTrigger.Configuration.JourneyID.ValueString()
			} else {
				journeyID = nil
			}
			var sourceId3 string
			sourceId3 = triggersItem.FlowsTrigger.Configuration.SourceID.ValueString()

			configuration6 := shared.FlowsTriggerConfiguration{
				JourneyID: journeyID,
				SourceID:  sourceId3,
			}
			id9 := new(string)
			if !triggersItem.FlowsTrigger.ID.IsUnknown() && !triggersItem.FlowsTrigger.ID.IsNull() {
				*id9 = triggersItem.FlowsTrigger.ID.ValueString()
			} else {
				id9 = nil
			}
			typeVar7 := shared.FlowsTriggerType(triggersItem.FlowsTrigger.Type.ValueString())
			flowsTrigger := shared.FlowsTrigger{
				Configuration: configuration6,
				ID:            id9,
				Type:          typeVar7,
			}
			triggers = append(triggers, shared.AnyTrigger{
				FlowsTrigger: &flowsTrigger,
			})
		}
	}
	version := new(float64)
	if !r.Version.IsUnknown() && !r.Version.IsNull() {
		*version = r.Version.ValueFloat64()
	} else {
		version = nil
	}
	var workflowContext *shared.WorkflowContext
	if r.WorkflowContext != nil {
		taskID := new(string)
		if !r.WorkflowContext.TaskID.IsUnknown() && !r.WorkflowContext.TaskID.IsNull() {
			*taskID = r.WorkflowContext.TaskID.ValueString()
		} else {
			taskID = nil
		}
		var workflowID string
		workflowID = r.WorkflowContext.WorkflowID.ValueString()

		workflowRole := shared.WorkflowContextRole(r.WorkflowContext.WorkflowRole.ValueString())
		workflowContext = &shared.WorkflowContext{
			TaskID:       taskID,
			WorkflowID:   workflowID,
			WorkflowRole: workflowRole,
		}
	}
	out := shared.AutomationFlowInput{
		Manifest:          manifest,
		Actions:           actions,
		Conditions:        conditions,
		DisableDetails:    disableDetails,
		Enabled:           enabled,
		EntitySchema:      entitySchema,
		FlowName:          flowName,
		MaxExecutions:     maxExecutions,
		Schedules:         schedules,
		SystemFlow:        systemFlow,
		TriggerConditions: triggerConditions,
		Triggers:          triggers,
		Version:           version,
		WorkflowContext:   workflowContext,
	}

	return &out, diags
}
