// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type CartCheckoutConfigMappingAttributes struct {
	MappingAttributeV2 *MappingAttributeV21 `tfsdk:"mapping_attribute_v2"`
	MappingAttribute   *MappingAttribute    `tfsdk:"mapping_attribute"`
}
