// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type OperationObjectNodeUniq3 struct {
	Boolean    types.Bool     `tfsdk:"boolean"`
	ArrayOfstr []types.String `tfsdk:"array_ofstr"`
}
