// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type EntityOperationTrigger2 struct {
	Added   *DiffAdded `tfsdk:"added"`
	Deleted *DiffAdded `tfsdk:"deleted"`
	Updated *DiffAdded `tfsdk:"updated"`
}
