// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type RelationAttribute struct {
	Mode                    types.String                   `tfsdk:"mode"`
	RelatedTo               map[string]types.String        `tfsdk:"related_to"`
	SourceFilter            *RelationAttributeSourceFilter `tfsdk:"source_filter"`
	Target                  types.String                   `tfsdk:"target"`
	TargetTags              []types.String                 `tfsdk:"target_tags"`
	TargetTagsIncludeSource types.Bool                     `tfsdk:"target_tags_include_source"`
}
