// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type SourceFilter struct {
	Attribute   types.String `tfsdk:"attribute"`
	Limit       types.Int64  `tfsdk:"limit"`
	RelationTag types.String `tfsdk:"relation_tag"`
	Schema      types.String `tfsdk:"schema"`
	Self        types.Bool   `tfsdk:"self"`
	Tag         types.String `tfsdk:"tag"`
}
