// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type TriggerConditionValue1 struct {
	Str           types.String   `tfsdk:"str"`
	Number        types.Number   `tfsdk:"number"`
	ArrayOfstr    []types.String `tfsdk:"array_ofstr"`
	ArrayOfnumber []types.Number `tfsdk:"array_ofnumber"`
}
