// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type OrCondition struct {
	DollarOr []types.Object `tfsdk:"dollar_or"`
}
