// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type OperationNode1 struct {
	OperationObjectNode *OperationObjectNode1 `tfsdk:"operation_object_node"`
	Any                 types.String          `tfsdk:"any"`
}
