// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type TriggerWorkflowConfig1 struct {
	AssignSteps    []AssignUsersToStep         `tfsdk:"assign_steps"`
	Assignees      []types.String              `tfsdk:"assignees"`
	Conditions     []TriggerWorkflowCondition1 `tfsdk:"conditions"`
	TargetWorkflow types.String                `tfsdk:"target_workflow"`
}
