// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type MappingAttributes struct {
	MappingAttribute   *MappingAttribute   `tfsdk:"mapping_attribute"`
	MappingAttributeV2 *MappingAttributeV2 `tfsdk:"mapping_attribute_v2"`
}
