// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type FilterConditionOnEvent struct {
	MapOfArrayOfTwo map[string][]Two `tfsdk:"map_of_array_of_two"`
	OrCondition     *OrCondition     `tfsdk:"or_condition"`
}
