// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type SendEmailConfigAttachments struct {
	SourceFilter *SendEmailConfigAttachmentsSourceFilter `tfsdk:"source_filter"`
}
