// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type MappingConfigRef struct {
	ConfigID types.String `tfsdk:"config_id"`
	TargetID types.String `tfsdk:"target_id"`
	Version  types.Number `tfsdk:"version"`
}
