// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Diff struct {
	Any types.String `tfsdk:"any"`
	Two *Two         `tfsdk:"two"`
}
