// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type EntityOperationTrigger struct {
	Configuration EntityOperationTriggerConfiguration `tfsdk:"configuration"`
	Type          types.String                        `tfsdk:"type"`
}
