// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ActionCondition struct {
	EvaluationResult types.Bool           `tfsdk:"evaluation_result"`
	ID               types.String         `tfsdk:"id"`
	ScheduleID       types.String         `tfsdk:"schedule_id"`
	Statements       []ConditionStatement `tfsdk:"statements"`
}
