// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type AnyTrigger struct {
	Any                    types.String            `tfsdk:"any" tfPlanOnly:"true"`
	APISubmissionTrigger   *APISubmissionTrigger   `tfsdk:"api_submission_trigger" tfPlanOnly:"true"`
	EntityManualTrigger    *EntityManualTrigger    `tfsdk:"entity_manual_trigger" tfPlanOnly:"true"`
	EntityOperationTrigger *EntityOperationTrigger `tfsdk:"entity_operation_trigger" tfPlanOnly:"true"`
	FrontendSubmitTrigger  *FrontendSubmitTrigger  `tfsdk:"frontend_submit_trigger" tfPlanOnly:"true"`
	JourneySubmitTrigger   *JourneySubmitTrigger   `tfsdk:"journey_submit_trigger" tfPlanOnly:"true"`
	ReceivedEmailTrigger   *ReceivedEmailTrigger   `tfsdk:"received_email_trigger" tfPlanOnly:"true"`
}
