// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Diff struct {
	Any types.String `tfsdk:"any" tfPlanOnly:"true"`
	Two *Two         `tfsdk:"two" tfPlanOnly:"true"`
}
