// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type EcpConfig struct {
	FileConfig *FileConfig  `tfsdk:"file_config"`
	Origin     types.String `tfsdk:"origin"`
}
