// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type FlowsTriggerConfiguration struct {
	JourneyID types.String `tfsdk:"journey_id"`
	SourceID  types.String `tfsdk:"source_id"`
}
