// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type JourneySubmitTrigger struct {
	Configuration JourneySubmitTriggerConfiguration `tfsdk:"configuration"`
	ID            types.String                      `tfsdk:"id"`
	Type          types.String                      `tfsdk:"type"`
}
