// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NewEmailThreadTriggerConfiguration struct {
	Direction      types.String   `tfsdk:"direction"`
	SharedInboxIds []types.String `tfsdk:"shared_inbox_ids"`
}
