// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type PrefixCondition struct {
	Prefix types.String `tfsdk:"prefix"`
}
