// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type WorkflowContext struct {
	TaskID       types.String `tfsdk:"task_id"`
	WorkflowID   types.String `tfsdk:"workflow_id"`
	WorkflowRole types.String `tfsdk:"workflow_role"`
}
