// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteFlowRequest struct {
	// Automation Workflow ID
	FlowID string `pathParam:"style=simple,explode=false,name=flow_id"`
}

type DeleteFlowResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
