// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotautomation/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetFlowPathParams struct {
	// Automation Workflow ID
	FlowID string `pathParam:"style=simple,explode=false,name=flow_id"`
}

type GetFlowRequest struct {
	PathParams GetFlowPathParams
}

type GetFlowResponse struct {
	// The returned automation flow
	AutomationFlow *shared.AutomationFlow
	ContentType    string
	StatusCode     int
	RawResponse    *http.Response
}
